"""PROPOSED v2.1 capability contracts and mechanics; production bindings absent."""

from .models import (
    CANDIDATE_SCHEMA_VERSION,
    CONTRACT_STATE,
    PROVIDER_SCHEMA_VERSION,
    AnyCapabilityEnvelope,
    CandidateDTO,
    CapabilityContractError,
    CapabilityEnvelope,
    CapabilityOutcome,
    CapabilityRefusalReason,
    ClausePurpose,
    ContractAuthorityIntent,
    ContractAuthorityResult,
    ContractResolutionUnavailable,
    DeclaredMemberships,
    ProviderCapabilityEnvelope,
    parse_envelope,
    parse_request,
    parse_result,
)
from .service import CapabilityService, CapabilitySourcePort

__all__ = [
    "CANDIDATE_SCHEMA_VERSION",
    "CONTRACT_STATE",
    "PROVIDER_SCHEMA_VERSION",
    "AnyCapabilityEnvelope",
    "ClausePurpose",
    "ContractAuthorityIntent",
    "ContractAuthorityResult",
    "ContractResolutionUnavailable",
    "ProviderCapabilityEnvelope",
    "CapabilityContractError",
    "CapabilityEnvelope",
    "CapabilityOutcome",
    "CapabilityRefusalReason",
    "CapabilityService",
    "CapabilitySourcePort",
    "CandidateDTO",
    "DeclaredMemberships",
    "parse_envelope",
    "parse_request",
    "parse_result",
]
