-- Owner-only migration. Runtime may SELECT designation, INSERT technical query audit.
-- No default grant/designation. Source installer/revoker takes MZO_HUMAN_TENANT
-- FOR UPDATE before changing designation rows, matching the AUTH invalidation lock.
CREATE TABLE MZO_AUTH_PRODUCER_DESIGNATION (
 TENANT_ text NOT NULL, DIGEST_ char(64) NOT NULL, RECORD_ text NOT NULL,
 PRIMARY KEY(TENANT_,DIGEST_),
 CHECK(octet_length(RECORD_)<=65536)
);
CREATE TABLE MZO_AUTH_PRODUCER_QUERY (
 TENANT_ text NOT NULL, QUERY_ text NOT NULL, QUERY_DIGEST_ char(64) NOT NULL,
 DESIGNATION_DIGEST_ char(64) NOT NULL, ACQUISITION_ text NOT NULL,
 OBSERVED_ timestamptz NOT NULL DEFAULT clock_timestamp(),
 PRIMARY KEY(TENANT_,QUERY_),
 FOREIGN KEY(TENANT_,DESIGNATION_DIGEST_) REFERENCES MZO_AUTH_PRODUCER_DESIGNATION(TENANT_,DIGEST_)
);
REVOKE ALL ON MZO_AUTH_PRODUCER_DESIGNATION,MZO_AUTH_PRODUCER_QUERY FROM PUBLIC;
