-- P2: owner-installed, same native schema. No default qualification or production grant.
CREATE TABLE MZO_HUMAN_CONSUMER_DATABASE (
  TENANT_ varchar(255) PRIMARY KEY REFERENCES MZO_HUMAN_TENANT(TENANT_),
  BINDING_ text NOT NULL
);
CREATE TABLE MZO_HUMAN_CONSUMER_TRUST (
  TENANT_ varchar(255) NOT NULL REFERENCES MZO_HUMAN_CONSUMER_DATABASE(TENANT_),
  KEY_ID_ varchar(255) NOT NULL, DESIGNATION_ text NOT NULL,
  PRIMARY KEY(TENANT_,KEY_ID_)
);
CREATE TABLE MZO_HUMAN_CONSUMER_REVOKED (
  TENANT_ varchar(255) NOT NULL, KEY_ID_ varchar(255) NOT NULL,
  GENERATION_ bigint NOT NULL CHECK(GENERATION_>0),
  PRIMARY KEY(TENANT_,KEY_ID_),
  FOREIGN KEY(TENANT_,KEY_ID_) REFERENCES MZO_HUMAN_CONSUMER_TRUST(TENANT_,KEY_ID_)
);
CREATE TABLE MZO_HUMAN_CONSUMER_QUALIFICATION (
  TENANT_ varchar(255) NOT NULL REFERENCES MZO_HUMAN_CONSUMER_DATABASE(TENANT_),
  GENERATION_ bigint NOT NULL CHECK(GENERATION_>0),
  AUTHORITY_REV_ bigint NOT NULL CHECK(AUTHORITY_REV_>=0),
  QUALIFICATION_ varchar(255) NOT NULL, ENVELOPE_ text NOT NULL,
  PRIMARY KEY(TENANT_,GENERATION_), UNIQUE(TENANT_,QUALIFICATION_)
);
CREATE TABLE MZO_HUMAN_CONSUMER_HEAD (
  TENANT_ varchar(255) PRIMARY KEY REFERENCES MZO_HUMAN_CONSUMER_DATABASE(TENANT_),
  GENERATION_ bigint NOT NULL CHECK(GENERATION_>=0),
  QUALIFICATION_GENERATION_ bigint,
  FOREIGN KEY(TENANT_,QUALIFICATION_GENERATION_) REFERENCES MZO_HUMAN_CONSUMER_QUALIFICATION(TENANT_,GENERATION_)
);
CREATE TABLE MZO_HUMAN_CONSUMER_POINTER (
  TENANT_ varchar(255) NOT NULL, SCOPE_DIGEST_ char(64) NOT NULL,
  TASK_ varchar(255) NOT NULL, COMMAND_ varchar(255) NOT NULL,
  EXECUTION_ varchar(255) NOT NULL, GENERATION_ bigint NOT NULL,
  POINTER_ text NOT NULL,
  PRIMARY KEY(TENANT_,TASK_,COMMAND_),
  FOREIGN KEY(TENANT_,GENERATION_) REFERENCES MZO_HUMAN_CONSUMER_QUALIFICATION(TENANT_,GENERATION_),
  FOREIGN KEY(TENANT_,TASK_,COMMAND_) REFERENCES MZO_HUMAN_RECEIPT(TENANT_,TASK_,COMMAND_) DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE MZO_HUMAN_CONSUMER_POINTER_HEAD (
  TENANT_ varchar(255) NOT NULL, SCOPE_DIGEST_ char(64) NOT NULL,
  EXECUTION_ varchar(255) NOT NULL, TASK_ varchar(255) NOT NULL, COMMAND_ varchar(255) NOT NULL,
  PRIMARY KEY(TENANT_,SCOPE_DIGEST_,EXECUTION_),
  FOREIGN KEY(TENANT_,TASK_,COMMAND_) REFERENCES MZO_HUMAN_CONSUMER_POINTER(TENANT_,TASK_,COMMAND_)
);
CREATE TABLE MZO_HUMAN_CONSUMER_LINK (
  TENANT_ varchar(255) NOT NULL, SCOPE_DIGEST_ char(64) NOT NULL,
  EXTERNAL_TASK_ varchar(255) NOT NULL, TASK_ varchar(255) NOT NULL, COMMAND_ varchar(255) NOT NULL,
  GENERATION_ bigint NOT NULL, LINK_ text NOT NULL, LINK_DIGEST_ char(64) NOT NULL,
  CONSUMER_KIND_ varchar(255) NOT NULL, CONSUMER_DIGEST_ char(64) NOT NULL,
  OUTCOME_ varchar(255) NOT NULL,
  PRIMARY KEY(TENANT_,SCOPE_DIGEST_,EXTERNAL_TASK_),
  FOREIGN KEY(TENANT_,TASK_,COMMAND_) REFERENCES MZO_HUMAN_CONSUMER_POINTER(TENANT_,TASK_,COMMAND_),
  FOREIGN KEY(TENANT_,GENERATION_) REFERENCES MZO_HUMAN_CONSUMER_QUALIFICATION(TENANT_,GENERATION_)
);
CREATE FUNCTION MZO_HUMAN_CONSUMER_IMMUTABLE() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'immutable consumer evidence'; END $$;
CREATE TRIGGER MZO_HUMAN_CONSUMER_DATABASE_IMMUTABLE BEFORE UPDATE OR DELETE OR TRUNCATE ON MZO_HUMAN_CONSUMER_DATABASE FOR EACH STATEMENT EXECUTE FUNCTION MZO_HUMAN_CONSUMER_IMMUTABLE();
CREATE TRIGGER MZO_HUMAN_CONSUMER_TRUST_IMMUTABLE BEFORE UPDATE OR DELETE OR TRUNCATE ON MZO_HUMAN_CONSUMER_TRUST FOR EACH STATEMENT EXECUTE FUNCTION MZO_HUMAN_CONSUMER_IMMUTABLE();
CREATE TRIGGER MZO_HUMAN_CONSUMER_REVOKED_IMMUTABLE BEFORE UPDATE OR DELETE OR TRUNCATE ON MZO_HUMAN_CONSUMER_REVOKED FOR EACH STATEMENT EXECUTE FUNCTION MZO_HUMAN_CONSUMER_IMMUTABLE();
CREATE TRIGGER MZO_HUMAN_CONSUMER_QUAL_IMMUTABLE BEFORE UPDATE OR DELETE OR TRUNCATE ON MZO_HUMAN_CONSUMER_QUALIFICATION FOR EACH STATEMENT EXECUTE FUNCTION MZO_HUMAN_CONSUMER_IMMUTABLE();
CREATE TRIGGER MZO_HUMAN_CONSUMER_POINTER_IMMUTABLE BEFORE UPDATE OR DELETE OR TRUNCATE ON MZO_HUMAN_CONSUMER_POINTER FOR EACH STATEMENT EXECUTE FUNCTION MZO_HUMAN_CONSUMER_IMMUTABLE();
CREATE TRIGGER MZO_HUMAN_CONSUMER_LINK_IMMUTABLE BEFORE UPDATE OR DELETE OR TRUNCATE ON MZO_HUMAN_CONSUMER_LINK FOR EACH STATEMENT EXECUTE FUNCTION MZO_HUMAN_CONSUMER_IMMUTABLE();
