-- E04 approved construction profile; owner-applied to the SAME CIB database/schema.
-- No executable designation, source grant or profile activation is bootstrapped here.
-- Runtime grants are installed/read back by AuthInstallation, never PUBLIC.
CREATE TABLE MZO_AUTH_INSTALLATION (
 TENANT_ varchar(255) PRIMARY KEY REFERENCES MZO_HUMAN_TENANT(TENANT_),
 INCARNATION_ varchar(255) NOT NULL, REV_ bigint NOT NULL CHECK(REV_>0),
 SCOPE_ text NOT NULL, BINDING_ text NOT NULL, QUALIFICATION_ text NOT NULL
);
CREATE TABLE MZO_AUTH_TRUST (
 TENANT_ varchar(255) NOT NULL REFERENCES MZO_AUTH_INSTALLATION(TENANT_),
 KEY_ID_ varchar(255) NOT NULL, DESIGNATION_ text NOT NULL,
 PRIMARY KEY(TENANT_,KEY_ID_)
);
CREATE TABLE MZO_AUTH_REVOKED_KEY (
 TENANT_ varchar(255) NOT NULL REFERENCES MZO_AUTH_INSTALLATION(TENANT_),
 KEY_ID_ varchar(255) NOT NULL, REV_ bigint NOT NULL CHECK(REV_>0),
 PRIMARY KEY(TENANT_,KEY_ID_)
);
CREATE TABLE MZO_AUTH_INPUT_HEAD (
 TENANT_ varchar(255) NOT NULL REFERENCES MZO_AUTH_INSTALLATION(TENANT_),
 KIND_ varchar(32) NOT NULL CHECK(KIND_ IN ('actor','resource_authority','guide','start_facts','document_custody','document_policy','audit_intent')),
 RESOURCE_ varchar(255) NOT NULL, GENERATION_ bigint NOT NULL CHECK(GENERATION_>0),
 STATE_ varchar(16) NOT NULL CHECK(STATE_ IN ('active','frozen','revoked')),
 PUBLICATION_ varchar(255) NOT NULL, PUBLICATION_DIGEST_ char(64) NOT NULL,
 PUBLISHER_KEY_ varchar(255) NOT NULL, PUBLISHER_DIGEST_ char(64) NOT NULL,
 SOURCE_ text NOT NULL, PAYLOAD_ text, PAYLOAD_DIGEST_ char(64), VALID_UNTIL_ timestamptz NOT NULL,
 CHECK((STATE_='active')=(PAYLOAD_ IS NOT NULL)),
 CHECK((PAYLOAD_ IS NULL)=(PAYLOAD_DIGEST_ IS NULL)),
 PRIMARY KEY(TENANT_,KIND_,RESOURCE_)
);
CREATE TABLE MZO_AUTH_INPUT_VERSION (
 TENANT_ varchar(255) NOT NULL REFERENCES MZO_AUTH_INSTALLATION(TENANT_),
 KIND_ varchar(32) NOT NULL, RESOURCE_ varchar(255) NOT NULL, GENERATION_ bigint NOT NULL CHECK(GENERATION_>0),
 PUBLISHER_KEY_ varchar(255) NOT NULL, PUBLISHER_DIGEST_ char(64) NOT NULL,
 PUBLICATION_ varchar(255) NOT NULL, DIGEST_ char(64) NOT NULL, REQUEST_ text NOT NULL, RECEIPT_ text NOT NULL,
 PRIMARY KEY(TENANT_,KIND_,RESOURCE_,GENERATION_), UNIQUE(TENANT_,PUBLICATION_)
);
CREATE TABLE MZO_AUTH_GUIDE_CLAIM (
 TENANT_ varchar(255) NOT NULL REFERENCES MZO_AUTH_INSTALLATION(TENANT_),
 GUIDE_ varchar(255) NOT NULL, INTAKE_ varchar(255) NOT NULL,
 COMMAND_ varchar(255) NOT NULL, DIGEST_ char(64) NOT NULL,
 PRINCIPAL_ varchar(255) NOT NULL, INSTANCE_ varchar(255) NOT NULL, CASE_ varchar(255) NOT NULL,
 DEFINITION_ text NOT NULL,
 PRIMARY KEY(TENANT_,GUIDE_), UNIQUE(TENANT_,INTAKE_), UNIQUE(TENANT_,INSTANCE_), UNIQUE(TENANT_,CASE_)
);
CREATE TABLE MZO_AUTH_INSTANCE_HEAD (
 TENANT_ varchar(255) NOT NULL REFERENCES MZO_AUTH_INSTALLATION(TENANT_),
 INSTANCE_ varchar(255) NOT NULL, REV_ bigint NOT NULL CHECK(REV_>=0),
 GENERATION_ bigint NOT NULL CHECK(GENERATION_>=0), CURRENT_REQUEST_ varchar(255),
 PRIMARY KEY(TENANT_,INSTANCE_),
 FOREIGN KEY(TENANT_,INSTANCE_) REFERENCES MZO_AUTH_GUIDE_CLAIM(TENANT_,INSTANCE_)
);
CREATE TABLE MZO_AUTH_DOC_OCCURRENCE (
 TENANT_ varchar(255) NOT NULL REFERENCES MZO_AUTH_INSTALLATION(TENANT_),
 REQUEST_ varchar(255) NOT NULL, INSTANCE_ varchar(255) NOT NULL,
 GENERATION_ bigint NOT NULL CHECK(GENERATION_>0), REV_ bigint NOT NULL CHECK(REV_>=0),
 PRODUCER_TASK_ varchar(255) NOT NULL, PUBLICATION_TASK_ varchar(255),
 SUBSCRIPTION_ varchar(255), STATE_ varchar(32) NOT NULL CHECK(STATE_ IN
 ('created','awaiting_publication_worker','bound','consumed','expired','cancelled','replaced')),
 RECORD_ text NOT NULL,
 PRIMARY KEY(TENANT_,REQUEST_), UNIQUE(TENANT_,INSTANCE_,PRODUCER_TASK_),
 UNIQUE(TENANT_,INSTANCE_,GENERATION_), UNIQUE(TENANT_,PUBLICATION_TASK_), UNIQUE(TENANT_,SUBSCRIPTION_),
 FOREIGN KEY(TENANT_,INSTANCE_) REFERENCES MZO_AUTH_INSTANCE_HEAD(TENANT_,INSTANCE_)
);
CREATE TABLE MZO_AUTH_EFFECT_RECEIPT (
 TENANT_ varchar(255) NOT NULL REFERENCES MZO_AUTH_INSTALLATION(TENANT_),
 COMMAND_ varchar(255) NOT NULL, DIGEST_ char(64) NOT NULL,
 OPERATION_ varchar(32) NOT NULL CHECK(OPERATION_ IN ('auth.start','auth.documents.respond')),
 PRINCIPAL_ varchar(255) NOT NULL, ADMISSION_ varchar(255) NOT NULL,
 REQUEST_ varchar(255), RECEIPT_ text NOT NULL,
 CHECK((OPERATION_='auth.documents.respond')=(REQUEST_ IS NOT NULL)),
 PRIMARY KEY(TENANT_,COMMAND_), UNIQUE(TENANT_,REQUEST_)
);
REVOKE ALL ON TABLE MZO_AUTH_INSTALLATION,MZO_AUTH_TRUST,MZO_AUTH_REVOKED_KEY,
 MZO_AUTH_INPUT_HEAD,MZO_AUTH_INPUT_VERSION,MZO_AUTH_GUIDE_CLAIM,
 MZO_AUTH_INSTANCE_HEAD,MZO_AUTH_DOC_OCCURRENCE,MZO_AUTH_EFFECT_RECEIPT FROM PUBLIC;
