-- E03 deployment owner applies to the actual engine schema; no grants/activation seeded.
CREATE TABLE MZO_HUMAN_ASSIGNMENT_INSTALLATION (
 TENANT_ varchar(255) PRIMARY KEY REFERENCES MZO_HUMAN_TENANT(TENANT_),
 ENVIRONMENT_ varchar(255) NOT NULL, ENGINE_NAME_ varchar(255) NOT NULL,
 DATABASE_INCARNATION_ varchar(255) NOT NULL,
 DATABASE_OID_ oid NOT NULL, ENGINE_SCHEMA_OID_ oid NOT NULL, ENGINE_LOGIN_OID_ oid NOT NULL,
 CONFIGURATION_DIGEST_ char(64) NOT NULL, DEPLOYMENT_RECEIPT_REF_ varchar(255) NOT NULL,
 DEPLOYMENT_RECEIPT_DIGEST_ char(64) NOT NULL,
 STATE_ varchar(16) NOT NULL CHECK(STATE_ IN ('qualified','disabled')),
 REVISION_ bigint NOT NULL CHECK(REVISION_>=0), VALID_UNTIL_ bigint NOT NULL
);
CREATE TABLE MZO_HUMAN_ASSIGNMENT_GENERATION (
 TENANT_ varchar(255) PRIMARY KEY REFERENCES MZO_HUMAN_TENANT(TENANT_),
 SOURCE_REVISION_ bigint NOT NULL CHECK(SOURCE_REVISION_>=0), AUTHORITY_REVISION_ bigint NOT NULL CHECK(AUTHORITY_REVISION_>=0),
 GENERATION_DIGEST_ char(64) NOT NULL, STATE_ varchar(16) NOT NULL CHECK(STATE_ IN ('active','disabled')),
 GENERATION_ text NOT NULL CHECK(octet_length(GENERATION_)<=65536),
 ATTESTATION_ text NOT NULL CHECK(octet_length(ATTESTATION_)<=65536), VALID_UNTIL_ bigint NOT NULL
);
CREATE TABLE MZO_HUMAN_ASSIGNMENT_PUBLICATION (
 TENANT_ varchar(255) NOT NULL REFERENCES MZO_HUMAN_TENANT(TENANT_), PUBLICATION_ID_ varchar(255) NOT NULL,
 SOURCE_REVISION_ bigint NOT NULL CHECK(SOURCE_REVISION_>=0), OPERATION_ varchar(16) NOT NULL CHECK(OPERATION_ IN ('disable','replace')),
 REQUEST_DIGEST_ char(64) NOT NULL, REQUEST_ text NOT NULL CHECK(octet_length(REQUEST_)<=65536),
 RECEIPT_ text NOT NULL CHECK(octet_length(RECEIPT_)<=65536),
 PRIMARY KEY(TENANT_,PUBLICATION_ID_), UNIQUE(TENANT_,SOURCE_REVISION_,OPERATION_)
);
REVOKE ALL ON MZO_HUMAN_ASSIGNMENT_INSTALLATION,MZO_HUMAN_ASSIGNMENT_GENERATION,MZO_HUMAN_ASSIGNMENT_PUBLICATION FROM PUBLIC;
-- Runtime: SELECT-only installation; SELECT/INSERT/UPDATE generation; SELECT/INSERT publication.
-- Independently controlled deployment role alone owns installation writes and DDL.

-- C9 retained effect association and separately source-issued current receipt disclosure.
CREATE TABLE MZO_HUMAN_ASSIGNMENT_RECEIPT_RESOURCE (
 TENANT_ varchar(255) NOT NULL, TASK_ varchar(255) NOT NULL, COMMAND_ varchar(255) NOT NULL,
 DIGEST_ char(64) NOT NULL, PRINCIPAL_ varchar(255) NOT NULL, WORKLOAD_ varchar(255) NOT NULL,
 LINKAGE_ text NOT NULL CHECK(octet_length(LINKAGE_)<=65536),
 PRIMARY KEY(TENANT_,TASK_,COMMAND_),
 FOREIGN KEY(TENANT_,TASK_,COMMAND_) REFERENCES MZO_HUMAN_RECEIPT(TENANT_,TASK_,COMMAND_)
);
CREATE TABLE MZO_HUMAN_ASSIGNMENT_RECEIPT_DISCLOSURE (
 TENANT_ varchar(255) NOT NULL REFERENCES MZO_HUMAN_TENANT(TENANT_),TASK_ varchar(255) NOT NULL,COMMAND_ varchar(255) NOT NULL,
 SOURCE_REVISION_ bigint NOT NULL,DISCLOSURE_DIGEST_ char(64) NOT NULL,
 REQUEST_ text NOT NULL CHECK(octet_length(REQUEST_)<=65536),PRIMARY KEY(TENANT_,TASK_,COMMAND_)
);
CREATE TABLE MZO_HUMAN_ASSIGNMENT_RECEIPT_PUBLICATION (
 TENANT_ varchar(255) NOT NULL REFERENCES MZO_HUMAN_TENANT(TENANT_),PUBLICATION_ID_ varchar(255) NOT NULL,
 REQUEST_DIGEST_ char(64) NOT NULL,REQUEST_ text NOT NULL CHECK(octet_length(REQUEST_)<=65536),
 RECEIPT_ text NOT NULL CHECK(octet_length(RECEIPT_)<=65536),PRIMARY KEY(TENANT_,PUBLICATION_ID_)
);
REVOKE ALL ON MZO_HUMAN_ASSIGNMENT_RECEIPT_RESOURCE,MZO_HUMAN_ASSIGNMENT_RECEIPT_DISCLOSURE,MZO_HUMAN_ASSIGNMENT_RECEIPT_PUBLICATION FROM PUBLIC;
