-- Q2 additive projection schema. Apply once with a dedicated migration identity, never at startup.
-- Same database/transaction as CIB 2.1 and human-schema-postgres.sql. No ACT_* DDL.
-- No role/credential is provisioned by this file. PUBLIC receives no rights.
CREATE TABLE MZO_PORTAL_READ_CATALOG (
 TENANT_ varchar(255) NOT NULL, ENVIRONMENT_ varchar(255) NOT NULL,
 ENGINE_ varchar(255) NOT NULL, INCARNATION_ varchar(255) NOT NULL,
 CATALOG_ varchar(255) NOT NULL, REVISION_ bigint NOT NULL CHECK (REVISION_>=0),
 DIGEST_ char(64) NOT NULL, ARTIFACT_ text NOT NULL, PUBLICATION_ varchar(255) NOT NULL,
 SOURCE_ text NOT NULL, PUBLISHER_ varchar(255) NOT NULL, VALID_UNTIL_ timestamptz NOT NULL,
 PRIMARY KEY(TENANT_,ENVIRONMENT_,ENGINE_,INCARNATION_,CATALOG_,REVISION_)
);
CREATE TABLE MZO_PORTAL_READ_DESIGNATION (
 TENANT_ varchar(255) NOT NULL, ENVIRONMENT_ varchar(255) NOT NULL,
 ENGINE_ varchar(255) NOT NULL, INCARNATION_ varchar(255) NOT NULL,
 CATALOG_ varchar(255) NOT NULL, REVISION_ bigint NOT NULL CHECK (REVISION_>=0),
 DIGEST_ char(64) NOT NULL, PUBLICATION_ varchar(255) NOT NULL,
 SOURCE_ text NOT NULL, PUBLISHER_ varchar(255) NOT NULL, VALID_UNTIL_ timestamptz NOT NULL,
 REVOKED_ boolean NOT NULL,
 PRIMARY KEY(TENANT_,ENVIRONMENT_,ENGINE_,INCARNATION_,CATALOG_)
);
CREATE TABLE MZO_PORTAL_READ_MEMBERSHIP (
 TENANT_ varchar(255) NOT NULL, ENVIRONMENT_ varchar(255) NOT NULL,
 ENGINE_ varchar(255) NOT NULL, INCARNATION_ varchar(255) NOT NULL,
 PRINCIPAL_ varchar(255) NOT NULL, ISSUER_ text NOT NULL, SUBJECT_ varchar(255) NOT NULL,
 REVISION_ bigint NOT NULL CHECK (REVISION_>=0), PAYLOAD_ text NOT NULL,
 PUBLICATION_ varchar(255) NOT NULL, SOURCE_ text NOT NULL,
 PRIMARY KEY(TENANT_,ENVIRONMENT_,ENGINE_,INCARNATION_,PRINCIPAL_),
 UNIQUE(TENANT_,ENVIRONMENT_,ENGINE_,INCARNATION_,ISSUER_,SUBJECT_)
);
CREATE TABLE MZO_PORTAL_READ_RESOURCE (
 TENANT_ varchar(255) NOT NULL, ENVIRONMENT_ varchar(255) NOT NULL,
 ENGINE_ varchar(255) NOT NULL, INCARNATION_ varchar(255) NOT NULL,
 TASK_ varchar(64) NOT NULL, PAYLOAD_ text NOT NULL, PUBLICATION_ varchar(255) NOT NULL,
 SOURCE_ text NOT NULL,
 PRIMARY KEY(TENANT_,ENVIRONMENT_,ENGINE_,INCARNATION_,TASK_)
);
CREATE TABLE MZO_PORTAL_READ_REVOCATION (
 TENANT_ varchar(255) NOT NULL, ENVIRONMENT_ varchar(255) NOT NULL,
 ENGINE_ varchar(255) NOT NULL, INCARNATION_ varchar(255) NOT NULL,
 FINGERPRINT_ char(64) NOT NULL, REVISION_ bigint NOT NULL CHECK(REVISION_>=0),
 PUBLICATION_ varchar(255) NOT NULL,
 PRIMARY KEY(TENANT_,ENVIRONMENT_,ENGINE_,INCARNATION_,FINGERPRINT_)
);
CREATE TABLE MZO_PORTAL_READ_PUBLICATION_RECEIPT (
 TENANT_ varchar(255) NOT NULL, ENVIRONMENT_ varchar(255) NOT NULL,
 ENGINE_ varchar(255) NOT NULL, INCARNATION_ varchar(255) NOT NULL,
 PUBLICATION_ varchar(255) NOT NULL, DIGEST_ char(64) NOT NULL,
 KEY_FINGERPRINT_ char(64) NOT NULL, RECEIPT_ text NOT NULL,
 PRIMARY KEY(TENANT_,ENVIRONMENT_,ENGINE_,INCARNATION_,PUBLICATION_)
);
REVOKE ALL ON MZO_PORTAL_READ_CATALOG,MZO_PORTAL_READ_DESIGNATION,
 MZO_PORTAL_READ_MEMBERSHIP,MZO_PORTAL_READ_RESOURCE,MZO_PORTAL_READ_REVOCATION,
 MZO_PORTAL_READ_PUBLICATION_RECEIPT FROM PUBLIC;
-- Publication receiver alone may write these relations and MZO_HUMAN_TENANT REV_.
-- Its explicit resource fence uses TaskEntity.forceUpdate in the SAME engine transaction.
-- Read routes execute only prepared SELECT on the enlisted connection. The plugin's
-- runtime identity must be qualified separately; this DDL is not an authority grant.
