#!/usr/bin/env python3
"""CI gate + generator: the release-capability floor (audit §5, W-fillers).

Purpose
-------
Audit §5 names a hole: an override can hide a P0 regression from a release decision when nobody
recomputes "did this candidate actually get worse" against anything but a hand-maintained ledger. This
script closes that hole the same way `scripts/ci/generate_xfail_census.py` closed the xfail-count
drift hole (PLANS.md §0.8 finding W5): make "capability" a GENERATED number, derived at build time
from truths this repo *already* generates, never hand-recounted and pasted into prose.

Composite capability vector
----------------------------
"Capability" here is deliberately a composite of already-generated truths, not a new invented
number:

  - `xfail_total`      — the strict-xfail census TOTAL (`docs/xfail-census.json`, generated by
                          `generate_xfail_census.py`). More strict-xfails = more unproven properties
                          = less capability. Must not INCREASE.
  - `xfail_by_priority` — the census's own `per_classification` breakdown, narrowed to the
                          `AUTOMATABLE_CLASSES` priorities (`P0`/`P1`/`P2`) that census module
                          already reserves for exactly this purpose (today all real xfails are
                          `HUMAN_CEILING_CLASSES`, i.e. every priority bucket is 0 — see that
                          module's own comment). Each priority is compared INDEPENDENTLY of
                          `xfail_total`: this is what stops a P0 regression from hiding behind an
                          unrelated total improvement (e.g. one human-ceiling xfail fixed +1 P0
                          engineering-gap xfail introduced nets a FLAT or IMPROVED total while a
                          real regression slipped in — audit §5's exact "override hides a P0
                          regression" shape). Must not increase, per priority, regardless of total.
  - `unit_tests_passed` — the passing count of the unit suite, obtained in one of TWO modes:
                          * `--unit-junit <glob>` (what CI uses since 22/09/2026): sum of
                            `tests - failures - errors - skipped` over the JUnit reports the
                            `unit` job's 8 shards already publish (`unit-junit-<shard>.xml`).
                            The suite is measured ONCE per run, by the job that owns it; this gate
                            reads the artifact of the SAME run instead of re-running ~50 min of
                            runner time to recompute a number that already exists. The arithmetic
                            is pytest's own: a `<testsuite>`'s `tests` counts every reported case,
                            and `failures`/`errors`/`skipped` (pytest files xfail under `skipped`)
                            are exactly the cases that did not pass — measured identical to the
                            serial summary line on `tests/unit/agents` (2366 == 2366), in serial
                            and under `-n 2 --dist loadfile`.
                          * no flag (local `make release-floor-check`/`--write`): runs
                            `<python> -m pytest tests/ -q` itself (the same invocation `make test`
                            runs) and parses pytest's own final summary line.
                          Both modes are fail-closed in the same way: a red run (any
                          `failed`/`error`), an unparseable summary, a JUnit report that is missing,
                          unreadable or reports zero cases, aborts the whole gate before any
                          comparison is even attempted — neither a broken suite nor an absent
                          artifact may quietly produce a "lower but still passing" floor number, and
                          NOTHING may silently read as 0.
  - `fences_passing`    — which of the repo's already-wired AST/contract fences
                          (`FENCE_REGISTRY` below — the exact same scripts `artifact-validation`'s
                          CI job runs, invoked exactly as their own Makefile targets do) currently
                          exit 0. A previously-passing fence going dark is a capability regression:
                          "the fences must stay enabled" (mission requirement 3) is enforced by
                          requiring the candidate's passing set to be a SUPERSET of the baseline's.

Floor semantics — the deliberate departure from the census's exact-match pattern
----------------------------------------------------------------------------------
`generate_xfail_census.py --check` requires an EXACT match against the committed ledger (any drift,
better or worse, fails) because a census is a ledger — it should always mirror the tree precisely.
A release-capability gate is different in kind: it is a FLOOR, the worst acceptable state, not a
running tally. This script's `--check` therefore FAILS only when the candidate is BELOW the
committed baseline in some dimension, and PASSES on an exact hold OR a genuine improvement — exactly
mission requirement 4 ("fail on a real regression ... pass on genuine improvement or hold"). The
generation/commit MECHANISM still mirrors the census exactly: a pure generator, a `--write` mode that
regenerates the committed artifact (`docs/release-capability-floor.json`), and a `--check` mode (the
CI gate, default) that never mutates anything. Ratcheting the floor — up after a real fix lands, or
down only with deliberate, reviewed intent — is always an explicit `--write` + commit, never implicit.

Non-vacuity self-check
------------------------
Mirrors the AST fences' own "prove the gate can fail" discipline (e.g.
`check_start_process_fence.py`'s `fence_called_in` non-vacuity proof), applied to a comparator instead
of a scanner: before trusting any real measurement, `run_self_check()` feeds `compare_vectors` four
synthetic REGRESSED scenarios (total up; P0 up while total *improves*, the audit-hole shape above;
unit-tests down; a fence going dark) and two synthetic HELD/IMPROVED scenarios, and refuses to
proceed at all if any of the six doesn't produce the expected PASS/FAIL. A defanged comparator (e.g.
a stray `return []`) fails this self-check loudly instead of silently rubber-stamping every candidate.

Fail-closed contract
---------------------
- Any registered fence errors, `docs/xfail-census.json` is missing, or the unit-test measurement is
  red (`--write` mode) -> refuse to write; a baseline must never encode a known-broken measurement.
- The unit-test measurement is red (`--check` mode) -> FAIL immediately, before the floor
  comparison. In `--unit-junit` mode "red" also covers a measurement that never happened: no file
  matched the glob, a file is not parseable JUnit, or a report has zero cases.
- The self-check itself misbehaves -> FAIL immediately, before measuring anything real.
- `--check`: never mutates `docs/release-capability-floor.json`.

Usage
-----
    python scripts/ci/generate_release_floor.py --check     # local gate: re-runs the suite itself
    python scripts/ci/generate_release_floor.py --check --unit-junit 'unit-junit-*.xml'   # CI gate
    python scripts/ci/generate_release_floor.py --write      # regenerate docs/release-capability-floor.json
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import signal
import subprocess
import sys
import time
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from xml.etree import ElementTree

# scripts/ci/<file> -> parents[2] == repo root.
REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    # Explicit, idempotent sys.path insert so this module resolves the same dotted import whether it
    # is run directly (`python scripts/ci/generate_release_floor.py`, where sys.path[0] defaults to
    # scripts/ci, NOT the repo root) or imported by pytest (`pythonpath = ["."]` already puts the
    # repo root on sys.path there). Reuses the census's own P0/P1/P2 priority-name set below instead
    # of re-declaring the literal strings a second time (the exact hand-maintained-number drift risk
    # this whole script exists to avoid).
    sys.path.insert(0, str(REPO_ROOT))

from scripts.ci.generate_xfail_census import (  # noqa: E402
    AUTOMATABLE_CLASSES,
    DEFAULT_CENSUS_PATH,
)
from scripts.dev import run_engine_integration as process_groups  # noqa: E402

DEFAULT_FLOOR_PATH = "docs/release-capability-floor.json"

#: Priority buckets compared INDEPENDENTLY of `xfail_total` — sorted once, here, so an iteration
#: order downstream (JSON rendering, self-check fixtures) is deterministic and never depends on
#: frozenset hash order.
PRIORITIES: tuple[str, ...] = tuple(sorted(AUTOMATABLE_CLASSES))


# ---------------------------------------------------------------------------
# The already-wired generated-truth gates this floor composes from
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class FenceSpec:
    """One already-existing CI gate, invoked exactly as its own Makefile target does."""

    name: str
    argv: tuple[str, ...]  # argv[0] is a script path relative to repo root; rest are CLI flags


#: The exact 5 gates `artifact-validation` already runs in `.github/workflows/ci.yml`, named to
#: match their own Makefile targets 1:1 (`check-bpmn-error-allowlist`, `check-start-process-fence`,
#: `effect-chokepoint-fence`, `verify-amh-contract-pin`, `xfail-census-check`). Extending this tuple
#: is a deliberate, reviewed act — the exact same posture `check_start_process_fence.py`'s own
#: `SANCTIONED_RELATIVE_PATHS` takes on its allowlist.
FENCE_REGISTRY: tuple[FenceSpec, ...] = (
    FenceSpec("check-bpmn-error-allowlist", ("scripts/ci/check_bpmn_error_allowlist.py",)),
    FenceSpec("check-start-process-fence", ("scripts/ci/check_start_process_fence.py",)),
    FenceSpec("effect-chokepoint-fence", ("scripts/ci/check_effect_chokepoint_fence.py",)),
    FenceSpec("verify-amh-contract-pin", ("scripts/ci/verify_amh_contract_pin.py",)),
    FenceSpec("xfail-census-check", ("scripts/ci/generate_xfail_census.py", "--check")),
)


@dataclass(frozen=True)
class Violation:
    code: str
    detail: str

    def render(self) -> str:
        return f"[{self.code}] {self.detail}"


@dataclass(frozen=True)
class FenceResult:
    name: str
    ok: bool
    returncode: int
    stderr_tail: str


#: Safety-net bound, not a principal control — every registered fence is AST-only/stdlib-only and
#: finishes in low single-digit seconds on the real tree (measured: <2s each). A hang past this is
#: itself a FAIL, never a silent indefinite block (the fences run inside a CI job with its own
#: outer bound, but a runaway child here must still surface as a loud, attributable failure).
_FENCE_TIMEOUT_SECONDS = 120


def run_fence(repo_root: Path, spec: FenceSpec, python_exe: str) -> FenceResult:
    """Invoke one registered fence as a subprocess. Pure w.r.t. the caller — never raises on a
    non-zero exit or a timeout, that's exactly the signal this function exists to report."""
    script = repo_root / spec.argv[0]
    try:
        proc = subprocess.run(
            [python_exe, str(script), *spec.argv[1:]],
            cwd=repo_root,
            capture_output=True,
            text=True,
            stdin=subprocess.DEVNULL,
            timeout=_FENCE_TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired:
        return FenceResult(spec.name, False, -1, f"TIMEOUT after {_FENCE_TIMEOUT_SECONDS}s — treated as FAIL")
    tail_lines = (proc.stdout + proc.stderr).splitlines()[-5:]
    return FenceResult(spec.name, proc.returncode == 0, proc.returncode, "\n".join(tail_lines))


def measure_fences(repo_root: Path, python_exe: str) -> list[FenceResult]:
    return [run_fence(repo_root, spec, python_exe) for spec in FENCE_REGISTRY]


# ---------------------------------------------------------------------------
# Unit-test pass count (the one vector field with no pre-existing committed artifact)
# ---------------------------------------------------------------------------

#: Matches pytest's own short-summary tokens: "6839 passed", "3 failed", "1 error"/"2 errors",
#: "1 warning"/"3 warnings", "587 skipped", etc. — whatever pytest chooses to render, never a
#: hand-maintained pattern of our own.
_PYTEST_SUMMARY_TOKEN_RE = re.compile(
    r"(?P<count>\d+)\s+(?P<label>passed|failed|skipped|deselected|xfailed|xpassed|errors?|warnings?)"
)


def parse_pytest_summary_line(line: str) -> dict[str, int]:
    """Pure parser: pytest's final `-q` summary line -> {normalized_label: count}. `errors`/`warnings`
    normalize to their singular key so "1 error" and "2 errors" both land on counts["error"]."""
    counts: dict[str, int] = {}
    for match in _PYTEST_SUMMARY_TOKEN_RE.finditer(line):
        label = match.group("label")
        if label in ("errors", "warnings"):
            label = label[:-1]
        counts[label] = counts.get(label, 0) + int(match.group("count"))
    return counts


def evaluate_unit_tests(
    counts: dict[str, int], returncode: int, raw_line: str
) -> tuple[int | None, list[Violation]]:
    """Pure fail-closed decision: a non-zero exit, any `failed`/`error` count, or an unparseable
    summary line all refuse to produce a passed-count — never silently default to 0 or to whatever
    partial count happened to parse, since either would be misreported as a "regression" instead of
    the "measurement is not trustworthy" state it actually is."""
    violations: list[Violation] = []
    if returncode != 0:
        violations.append(
            Violation(
                "unit-tests-red",
                f"pytest exited {returncode} (non-zero) — {raw_line!r}; a red suite cannot produce "
                "a trustworthy capability measurement",
            )
        )
    if counts.get("failed", 0) or counts.get("error", 0):
        violations.append(
            Violation(
                "unit-tests-red",
                f"pytest summary reports failed={counts.get('failed', 0)} "
                f"error={counts.get('error', 0)} — {raw_line!r}",
            )
        )
    passed = counts.get("passed")
    if passed is None:
        violations.append(
            Violation(
                "unit-tests-unparseable",
                f"could not find a 'N passed' token in the pytest summary line: {raw_line!r}",
            )
        )
    if violations:
        return None, violations
    return passed, []


#: CI run 34733483424 measured 4973.97s for the >20k-test suite with coverage,
#: exceeding the obsolete 1800s budget calibrated to 12k tests. Two hours leaves
#: headroom without changing the selector or the fail-closed acceptance contract.
_UNIT_TESTS_TIMEOUT_SECONDS = 7200


def _run_unit_measurement(repo_root: Path, python_exe: str) -> subprocess.CompletedProcess[str]:
    # Reuse the existing owned process-group cleanup, but preserve this lane's exact
    # environment/argv/stdin. The engine runner's _run deliberately changes those.
    command = [python_exe, "-m", "pytest", "tests/", "-q"]
    process: subprocess.Popen[str] | None = None

    def close_spawned_group() -> None:
        if process is not None and process.pid in process_groups._pending_groups:
            process_groups._quiesce_group(process, process.pid)

    with process_groups._spawn_signal_guard(
        close_spawned_group, handlers={signal.SIGTERM: process_groups._signal_handler}
    ) as activate:
        try:
            process = subprocess.Popen(
                command,
                cwd=repo_root,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                stdin=subprocess.DEVNULL,
                start_new_session=True,
            )
            process_groups._record_pending(process.pid)
            activate()
            stdout, stderr = process.communicate(timeout=_UNIT_TESTS_TIMEOUT_SECONDS)
            return subprocess.CompletedProcess(command, process.returncode, stdout, stderr)
        finally:
            with process_groups._cleanup_signal_mask():
                close_spawned_group()


class UnitEvidenceError(RuntimeError):
    """Requested diagnostic retention failed; this is not a unit-suite verdict."""


def _create_unit_evidence(repo_root: Path, destination: Path) -> Path:
    try:
        if not destination.is_absolute() or any(
            path.is_symlink() for path in (destination, *destination.parents)
        ):
            raise ValueError("absolute non-symlink evidence destination required")
        destination = destination.resolve()
        if destination.is_relative_to(repo_root.resolve()):
            raise ValueError("unit evidence must be outside checkout")
        destination.mkdir(mode=0o700, exist_ok=False)
        destination.chmod(0o700)
        return destination
    except (OSError, ValueError) as exc:
        raise UnitEvidenceError("unit evidence destination refused") from exc


def _unit_source_identity(repo_root: Path) -> dict[str, Any]:
    # Record actual executing wrapper bytes even if a local checkout is dirty.
    # HEAD/tree never claim custody of uncommitted test or application changes.
    source: dict[str, Any] = {
        "files": {
            str(path): hashlib.sha256(path.read_bytes()).hexdigest()
            for path in (Path(__file__).resolve(), Path(process_groups.__file__).resolve())
        }
    }
    command = ["git", "--no-replace-objects", "-c", "core.fsmonitor=false"]
    try:
        identity = subprocess.run(
            [*command, "rev-parse", "HEAD", "HEAD^{tree}"],
            cwd=repo_root,
            capture_output=True,
            text=True,
            check=True,
            timeout=5,
        ).stdout.splitlines()
        if len(identity) != 2 or any(not re.fullmatch(r"[0-9a-f]{40,64}", item) for item in identity):
            raise ValueError("invalid source identity")
        clean = subprocess.run(
            [*command, "diff", "--quiet", "HEAD", "--"],
            cwd=repo_root,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=5,
        ).returncode
        if clean not in (0, 1):
            raise ValueError("source status unavailable")
        source.update(head=identity[0], tree=identity[1], tracked_checkout_clean=clean == 0)
    except (OSError, ValueError, subprocess.SubprocessError):
        source["git_identity_available"] = False
    return source


def _write_unit_evidence(
    destination: Path,
    metadata: dict[str, Any],
    stdout: str | bytes | None,
    stderr: str | bytes | None,
) -> None:
    def encoded(value: str | bytes | None) -> bytes:
        return value if isinstance(value, bytes) else (value or "").encode("utf-8")

    streams = {"stdout.txt": encoded(stdout), "stderr.txt": encoded(stderr)}
    metadata["streams"] = {
        name: {"bytes": len(raw), "sha256": hashlib.sha256(raw).hexdigest()} for name, raw in streams.items()
    }
    # Metadata is last: a partial write cannot masquerade as a complete packet.
    streams["measurement.json"] = (json.dumps(metadata, sort_keys=True, indent=2) + "\n").encode()
    for name, raw in streams.items():
        fd = os.open(destination / name, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600)
        with os.fdopen(fd, "wb") as output:
            output.write(raw)


def measure_unit_tests(
    repo_root: Path, python_exe: str, *, evidence_dir: Path | None = None
) -> tuple[dict[str, int], int, str]:
    """Measure the unchanged make-test invocation; optionally retain private diagnostics."""
    destination = _create_unit_evidence(repo_root, evidence_dir) if evidence_dir is not None else None
    metadata: dict[str, Any] = {}
    if destination is not None:
        metadata = {
            "argv": [python_exe, "-m", "pytest", "tests/", "-q"],
            "cwd": str(repo_root.resolve()),
            "source_before": _unit_source_identity(repo_root),
            "timeout_seconds": _UNIT_TESTS_TIMEOUT_SECONDS,
        }
    started = time.monotonic()

    def retain(stdout: str | bytes | None, stderr: str | bytes | None, **outcome: Any) -> None:
        if destination is not None:
            metadata.update(
                outcome,
                elapsed_seconds=time.monotonic() - started,
                source_after=_unit_source_identity(repo_root),
                pending_groups=sorted(process_groups._pending_groups),
            )
            _write_unit_evidence(destination, metadata, stdout, stderr)

    try:
        proc = _run_unit_measurement(repo_root, python_exe)
    except BaseException as exc:
        try:
            retain(
                getattr(exc, "stdout", None),
                getattr(exc, "stderr", None),
                returncode=None,
                timed_out=isinstance(exc, subprocess.TimeoutExpired),
                capture_complete=False,
                exception_type=type(exc).__name__,
            )
        except Exception:
            print("[release-floor] unit diagnostic retention failed", file=sys.stderr)
        if isinstance(exc, subprocess.TimeoutExpired):
            raw_line = f"TIMEOUT after {_UNIT_TESTS_TIMEOUT_SECONDS}s running pytest tests/ -q: {exc}"
            return {}, -1, raw_line
        raise
    output_lines = [ln for ln in (proc.stdout + proc.stderr).splitlines() if ln.strip()]
    raw_line = output_lines[-1] if output_lines else ""
    counts = parse_pytest_summary_line(raw_line)
    try:
        retain(proc.stdout, proc.stderr, returncode=proc.returncode, timed_out=False, capture_complete=True)
    except Exception as exc:
        _, violations = evaluate_unit_tests(counts, proc.returncode, raw_line)
        if not violations:
            raise UnitEvidenceError("unit diagnostic retention failed after successful measurement") from exc
        print(
            "[release-floor] unit diagnostic retention failed; original red result preserved", file=sys.stderr
        )
    return counts, proc.returncode, raw_line


# ---------------------------------------------------------------------------
# Unit-test pass count, mode 2: read the shards' JUnit instead of re-running the whole suite
# ---------------------------------------------------------------------------
#
# Why this mode exists (measured, 22/09/2026): the `unit` CI job already runs the ENTIRE unit suite,
# split across 8 shards with xdist, and already publishes `unit-junit-<shard>.xml` as the artifact
# `unit-shard-<shard>` — the same artifact the `quality` job downloads for the coverage gate. This
# gate was running `pytest tests/ -q` a SECOND time, in series, in its own job, purely to fill
# `unit_tests_passed`: ~50 min of runner wall clock per push (22 min already burned when run
# 35727033897 was cancelled). Reading the JUnit of the SAME run measures the same thing the same
# number of times as the suite actually ran — it does not measure less, it stops measuring twice.
#
# What it can NOT do is degrade quietly. A gate whose input is a file is a gate that reads 0 when
# the file is absent, and "0 passed" is >= no floor in the wrong direction only because 0 is a
# NUMBER: it would read as a catastrophic regression on `--check` (harmless) but as a floor of 0 on
# `--write` (a permanently defanged gate). So every not-a-measurement state — glob matched nothing,
# file unreadable/not JUnit, a report with `tests=0` (the shape a collection-time crash leaves),
# any `failures`/`errors` — is a hard violation with its own code, never a count.

#: Matches the `--junitxml=unit-junit-<shard>.xml` the `unit` job's matrix writes, after
#: `actions/download-artifact` with `merge-multiple: true` flattens every `unit-shard-*` into the
#: workspace root — the exact same shape the `quality` job's coverage step consumes.
DEFAULT_UNIT_JUNIT_GLOB = "unit-junit-*.xml"

#: The four `<testsuite>` attributes pytest always writes. `passed` is NOT among them: pytest's
#: JUnit has no such attribute, and `tests` counts every reported case, so the passing count is
#: `tests - failures - errors - skipped`. `skipped` is where pytest files BOTH real skips and
#: xfails (`<skipped type="pytest.xfail">`) — which is exactly right here, because the serial
#: summary line this replaces counts neither as `passed` either.
_JUNIT_COUNT_ATTRIBUTES: tuple[str, ...] = ("tests", "failures", "errors", "skipped")


class JunitParseError(ValueError):
    """A file matched the glob but is not a JUnit report we can trust. Never a verdict on the suite."""


@dataclass(frozen=True)
class JunitCounts:
    """One shard's JUnit report, reduced to the four counts the floor needs."""

    label: str
    tests: int
    failures: int
    errors: int
    skipped: int

    @property
    def passed(self) -> int:
        return self.tests - self.failures - self.errors - self.skipped


def parse_junit_counts(label: str, xml_text: str) -> JunitCounts:
    """Pure parser: one JUnit document -> `JunitCounts`. Sums EVERY `<testsuite>` in the document
    (pytest writes one under a `<testsuites>` root, but a merged/rewritten report may carry several,
    and silently reading only the first would undercount). Raises rather than guessing: a missing or
    non-numeric attribute is an unreadable measurement, not a zero."""
    try:
        root = ElementTree.fromstring(xml_text)
    except ElementTree.ParseError as exc:
        # ElementTree does not expand external entities and raises on undefined ones, so an
        # attacker-supplied XXE payload lands here as a parse error rather than a file read.
        raise JunitParseError(f"{label}: not parseable XML ({exc})") from exc
    suites = list(root.iter("testsuite"))  # includes `root` itself when it IS a <testsuite>
    if not suites:
        raise JunitParseError(f"{label}: no <testsuite> element — not a pytest JUnit report")
    totals = dict.fromkeys(_JUNIT_COUNT_ATTRIBUTES, 0)
    for suite in suites:
        for attribute in _JUNIT_COUNT_ATTRIBUTES:
            raw = suite.get(attribute)
            if raw is None:
                raise JunitParseError(f"{label}: <testsuite> has no {attribute!r} attribute")
            try:
                value = int(raw)
            except ValueError as exc:
                raise JunitParseError(f"{label}: <testsuite> {attribute}={raw!r} is not an integer") from exc
            if value < 0:
                raise JunitParseError(f"{label}: <testsuite> {attribute}={value} is negative")
            totals[attribute] += value
    counts = JunitCounts(label, **totals)
    if counts.passed < 0:
        raise JunitParseError(
            f"{label}: failures+errors+skipped ({counts.tests - counts.passed}) exceeds tests "
            f"({counts.tests}) — incoherent report"
        )
    return counts


def resolve_unit_junit_paths(repo_root: Path, pattern: str) -> list[Path]:
    """Expand the glob (relative to the repo root unless absolute) into a sorted, deterministic file
    list. Sorted so the evidence packet and the printed breakdown never depend on directory order."""
    raw = Path(pattern)
    if raw.is_absolute():
        anchor = Path(raw.anchor)
        matches = anchor.glob(str(raw.relative_to(anchor)))
    else:
        matches = repo_root.glob(pattern)
    return sorted(path for path in matches if path.is_file())


def evaluate_unit_junit(
    reports: Sequence[JunitCounts], read_errors: Sequence[str], pattern: str
) -> tuple[int | None, list[Violation]]:
    """Pure fail-closed decision over already-read reports. Same contract as `evaluate_unit_tests`:
    returns `(None, violations)` for every state that is not a trustworthy measurement, and never a
    partial or zero count."""
    violations: list[Violation] = []
    for message in read_errors:
        violations.append(Violation("unit-junit-unreadable", message))
    if not reports and not read_errors:
        violations.append(
            Violation(
                "unit-junit-missing",
                f"no JUnit report matched {pattern!r} — the unit suite was never measured for this "
                "candidate; an absent artifact must never read as 0 passed",
            )
        )
    for report in reports:
        if report.tests == 0:
            violations.append(
                Violation(
                    "unit-junit-empty",
                    f"{report.label}: reports tests=0 — a shard that collected nothing is a broken "
                    "measurement, not an empty one",
                )
            )
    for report in reports:
        if report.failures or report.errors:
            violations.append(
                Violation(
                    "unit-tests-red",
                    f"{report.label}: failures={report.failures} errors={report.errors} "
                    "(collection errors count here too) — a red suite cannot produce a trustworthy "
                    "capability measurement",
                )
            )
    if violations:
        return None, violations
    total = sum(report.passed for report in reports)
    if total <= 0:
        return None, [
            Violation(
                "unit-junit-empty",
                f"JUnit reports matching {pattern!r} sum to {total} passing tests — refusing to "
                "treat that as a measurement",
            )
        ]
    return total, []


def render_unit_junit_breakdown(reports: Sequence[JunitCounts], pattern: str) -> str:
    lines = [f"pattern: {pattern}"]
    for report in reports:
        lines.append(
            f"{report.label}: tests={report.tests} failures={report.failures} "
            f"errors={report.errors} skipped={report.skipped} passed={report.passed}"
        )
    lines.append(f"TOTAL passed: {sum(report.passed for report in reports)}")
    return "\n".join(lines) + "\n"


def measure_unit_tests_from_junit(
    repo_root: Path, pattern: str, *, evidence_dir: Path | None = None
) -> tuple[int | None, list[Violation], str]:
    """Read the shards' JUnit reports; optionally retain the same private diagnostics packet the
    subprocess mode retains (same directory contract, so the CI upload step is unchanged)."""
    destination = _create_unit_evidence(repo_root, evidence_dir) if evidence_dir is not None else None
    paths = resolve_unit_junit_paths(repo_root, pattern)
    reports: list[JunitCounts] = []
    read_errors: list[str] = []
    file_identity: dict[str, Any] = {}
    for path in paths:
        label = str(path.relative_to(repo_root)) if path.is_relative_to(repo_root) else str(path)
        try:
            raw = path.read_bytes()
        except OSError as exc:
            read_errors.append(f"{label}: cannot be read ({exc})")
            continue
        file_identity[label] = {"bytes": len(raw), "sha256": hashlib.sha256(raw).hexdigest()}
        try:
            reports.append(parse_junit_counts(label, raw.decode("utf-8", errors="replace")))
        except JunitParseError as exc:
            read_errors.append(str(exc))
    passed, violations = evaluate_unit_junit(reports, read_errors, pattern)
    breakdown = render_unit_junit_breakdown(reports, pattern)
    if destination is not None:
        metadata: dict[str, Any] = {
            "mode": "unit-junit",
            "pattern": pattern,
            "cwd": str(repo_root.resolve()),
            "source_after": _unit_source_identity(repo_root),
            "reports": file_identity,
            "counts": [
                {
                    "label": report.label,
                    "tests": report.tests,
                    "failures": report.failures,
                    "errors": report.errors,
                    "skipped": report.skipped,
                    "passed": report.passed,
                }
                for report in reports
            ],
            "unit_tests_passed": passed,
            "violations": [violation.render() for violation in violations],
        }
        try:
            _write_unit_evidence(destination, metadata, breakdown, "\n".join(read_errors))
        except Exception as exc:
            if not violations:
                raise UnitEvidenceError("unit diagnostic retention failed after successful read") from exc
            print(
                "[release-floor] unit diagnostic retention failed; original red result preserved",
                file=sys.stderr,
            )
    return passed, violations, breakdown.strip()


# ---------------------------------------------------------------------------
# The capability vector + the floor comparison
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CapabilityVector:
    xfail_total: int
    xfail_by_priority: dict[str, int]  # keys: PRIORITIES ("P0"/"P1"/"P2"); missing key == 0
    unit_tests_passed: int
    fences_passing: tuple[str, ...]  # sorted

    def to_json(self) -> dict[str, Any]:
        return {
            "xfail_total": self.xfail_total,
            "xfail_by_priority": dict(sorted(self.xfail_by_priority.items())),
            "unit_tests_passed": self.unit_tests_passed,
            "fences_passing": list(self.fences_passing),
        }

    @staticmethod
    def from_json(data: dict[str, Any]) -> CapabilityVector:
        return CapabilityVector(
            xfail_total=int(data["xfail_total"]),
            xfail_by_priority={str(k): int(v) for k, v in data["xfail_by_priority"].items()},
            unit_tests_passed=int(data["unit_tests_passed"]),
            fences_passing=tuple(sorted(data["fences_passing"])),
        )


def capability_vector_from_measurements(
    census: dict[str, Any],
    fence_results: Sequence[tuple[str, bool]],
    unit_tests_passed: int,
) -> CapabilityVector:
    per_classification = census.get("per_classification", {})
    xfail_by_priority = {p: int(per_classification.get(p, 0)) for p in PRIORITIES}
    fences_passing = tuple(sorted(name for name, ok in fence_results if ok))
    return CapabilityVector(
        xfail_total=int(census["total"]),
        xfail_by_priority=xfail_by_priority,
        unit_tests_passed=unit_tests_passed,
        fences_passing=fences_passing,
    )


def compare_vectors(candidate: CapabilityVector, baseline: CapabilityVector) -> list[Violation]:
    """The floor check. Pure — no I/O, fully unit-testable with synthetic vectors. Returns an empty
    list iff the candidate is at or above the floor in EVERY dimension."""
    violations: list[Violation] = []

    if candidate.xfail_total > baseline.xfail_total:
        violations.append(
            Violation(
                "xfail-total-regression",
                f"strict-xfail census total increased {baseline.xfail_total} -> "
                f"{candidate.xfail_total} — more unproven properties is a capability regression "
                "(audit §5)",
            )
        )

    for priority in PRIORITIES:
        base_p = baseline.xfail_by_priority.get(priority, 0)
        cand_p = candidate.xfail_by_priority.get(priority, 0)
        if cand_p > base_p:
            violations.append(
                Violation(
                    "xfail-priority-regression",
                    f"{priority}-classified xfail count increased {base_p} -> {cand_p}, checked "
                    "INDEPENDENTLY of xfail_total — this is what stops a P0 regression from hiding "
                    "behind an unrelated total improvement (audit §5's override-hides-a-P0-"
                    "regression hole)",
                )
            )

    if candidate.unit_tests_passed < baseline.unit_tests_passed:
        violations.append(
            Violation(
                "unit-tests-regression",
                f"passing unit-test count dropped {baseline.unit_tests_passed} -> "
                f"{candidate.unit_tests_passed}",
            )
        )

    missing_fences = sorted(set(baseline.fences_passing) - set(candidate.fences_passing))
    for name in missing_fences:
        violations.append(
            Violation(
                "fence-disabled",
                f"{name!r} was passing at the committed floor and is not passing now — a "
                "previously-enabled fence must never silently go dark",
            )
        )

    return violations


# ---------------------------------------------------------------------------
# Non-vacuity self-check — proves compare_vectors() can both FAIL and PASS before it is trusted
# ---------------------------------------------------------------------------


def _vec(
    xfail_total: int, p0: int, p1: int, p2: int, passed: int, fences: tuple[str, ...]
) -> CapabilityVector:
    return CapabilityVector(xfail_total, {"P0": p0, "P1": p1, "P2": p2}, passed, tuple(sorted(fences)))


#: (label, baseline, candidate, expect_at_least_one_violation). The 4 RED scenarios each regress
#: exactly ONE dimension while holding or IMPROVING every other — proving each dimension is gated
#: independently, not just "the vector as a whole looks worse". The P0 scenario is the audit-§5 hole
#: itself: total IMPROVES (10->9) while a P0 sneaks in (0->1); it must still fail.
SELF_CHECK_SCENARIOS: tuple[tuple[str, CapabilityVector, CapabilityVector, bool], ...] = (
    ("RED total-up", _vec(5, 0, 0, 0, 100, ("a", "b")), _vec(6, 0, 0, 0, 100, ("a", "b")), True),
    (
        "RED P0-up-behind-total-improvement",
        _vec(10, 0, 0, 0, 100, ("a", "b")),
        _vec(9, 1, 0, 0, 100, ("a", "b")),
        True,
    ),
    ("RED unit-tests-down", _vec(5, 0, 0, 0, 100, ("a", "b")), _vec(5, 0, 0, 0, 90, ("a", "b")), True),
    ("RED fence-disabled", _vec(5, 0, 0, 0, 100, ("a", "b")), _vec(5, 0, 0, 0, 100, ("a",)), True),
    ("GREEN exact-hold", _vec(5, 0, 0, 0, 100, ("a", "b")), _vec(5, 0, 0, 0, 100, ("a", "b")), False),
    (
        "GREEN genuine-improvement",
        _vec(5, 0, 0, 0, 100, ("a", "b")),
        _vec(4, 0, 0, 0, 110, ("a", "b", "c")),
        False,
    ),
)


def run_self_check() -> list[Violation]:
    violations: list[Violation] = []
    for label, baseline, candidate, expect_violation in SELF_CHECK_SCENARIOS:
        got_violation = bool(compare_vectors(candidate, baseline))
        if got_violation != expect_violation:
            wanted = "FAIL" if expect_violation else "PASS"
            got = "FAILED" if got_violation else "PASSED"
            violations.append(
                Violation(
                    "self-check-vacuous",
                    f"scenario {label!r}: expected compare_vectors to {wanted} but it {got} — the "
                    "comparator is vacuous or broken; refusing to trust any real measurement",
                )
            )
    return violations


# ---------------------------------------------------------------------------
# Baseline document serialization
# ---------------------------------------------------------------------------


def build_floor_document(vector: CapabilityVector) -> dict[str, Any]:
    return {
        "generated_by": "scripts/ci/generate_release_floor.py",
        "semantics": (
            "FLOOR (non-regression), not an exact-match ledger: --check FAILS only when the "
            "candidate vector is BELOW this baseline in some dimension; it PASSES on an exact hold "
            "or a genuine improvement. Ratchet the floor explicitly via --write — up after a real "
            "fix, or down only with deliberate, reviewed intent — never implicitly."
        ),
        "capability_vector": vector.to_json(),
        "sources": {
            "xfail_total / xfail_by_priority": (
                f"{DEFAULT_CENSUS_PATH} ('total', 'per_classification.P0'/'P1'/'P2'); trusted only "
                "once the 'xfail-census-check' fence below proves it is not stale."
            ),
            "unit_tests_passed": (
                "with `--unit-junit <glob>` (what CI uses): sum of `tests - failures - errors - "
                "skipped` over the `unit` job's own `unit-junit-<shard>.xml` reports, from the same "
                "run — the suite is measured once, by the job that owns it. Without the flag "
                "(local runs): final summary line of `<python> -m pytest tests/ -q`, the same "
                "invocation `make test` runs, executed by this script itself. Either way a red "
                "suite — or, in JUnit mode, a missing/unreadable/empty report — aborts the whole "
                "gate before any comparison."
            ),
            "fences_passing": (
                "each name's own script/mode, invoked exactly as its Makefile target does: "
                + "; ".join(f"{s.name} -> {' '.join(s.argv)}" for s in FENCE_REGISTRY)
            ),
        },
    }


def render_floor_json(doc: dict[str, Any]) -> str:
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="generate_release_floor",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=(
            "Generate/verify the committed release-capability floor (audit §5): a composite of "
            "the strict-xfail census, its P0/P1/P2 automatable subset, the passing unit-test "
            "count, and the repo's already-wired AST/contract fences. Fail-closed: an unreadable "
            "census, a red unit-test run, or a broken comparator abort BEFORE any floor comparison."
        ),
        epilog=(
            "modes\n"
            "  --check (default)  measure the current tree; FAIL if it is below the committed\n"
            "                     docs/release-capability-floor.json in any dimension.\n"
            "  --write            measure the current tree and overwrite the committed floor\n"
            "                     (refuses to write if any fence is failing or unit tests are red).\n"
            "\n"
            "unit-test source\n"
            "  --unit-junit GLOB  read the passing count off the unit job's published JUnit\n"
            "                     reports instead of re-running the suite in this process.\n"
        ),
    )
    parser.add_argument("--repo-root", default=str(REPO_ROOT), help="Repository root.")
    parser.add_argument("--floor-path", default=DEFAULT_FLOOR_PATH, help=f"default: {DEFAULT_FLOOR_PATH}")
    parser.add_argument("--census-path", default=DEFAULT_CENSUS_PATH, help=f"default: {DEFAULT_CENSUS_PATH}")
    parser.add_argument(
        "--python",
        default=sys.executable,
        help="Interpreter used for the fence + pytest subprocess measurements (default: sys.executable).",
    )
    parser.add_argument(
        "--unit-junit",
        metavar="GLOB",
        help=(
            "Read `unit_tests_passed` from the unit job's already-published JUnit reports "
            f"(e.g. {DEFAULT_UNIT_JUNIT_GLOB!r}) instead of re-running the whole suite here. "
            "Fail-closed: no match, an unreadable report, a report with zero cases, or any "
            "failure/error is a hard FAIL — never a count."
        ),
    )
    parser.add_argument(
        "--unit-evidence-dir",
        type=Path,
        help="New private directory outside checkout for captured unit diagnostics (no environment dump).",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="Verify only (default if neither flag given).")
    mode.add_argument("--write", action="store_true", help="Regenerate and overwrite the committed floor.")
    return parser


def _resolve(repo_root: Path, raw: str) -> Path:
    path = Path(raw)
    return path if path.is_absolute() else repo_root / path


def main(argv: Sequence[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    repo_root = Path(args.repo_root).resolve()
    floor_path = _resolve(repo_root, args.floor_path)
    census_path = _resolve(repo_root, args.census_path)

    self_check_violations = run_self_check()
    if self_check_violations:
        print("[release-floor] SELF-CHECK FAIL — comparator is vacuous/broken:", file=sys.stderr)
        for v in self_check_violations:
            print(f"  - {v.render()}", file=sys.stderr)
        return 1
    print(
        f"[release-floor] self-check: {len(SELF_CHECK_SCENARIOS)} scenarios "
        "(4 RED + 2 GREEN) behaved as expected (non-vacuity proof)."
    )

    # Fail fast in --check mode: there is nothing to compare against, so skip the ~minute-scale
    # fence + unit-test measurement below entirely rather than pay that cost only to fail anyway.
    if not args.write and not floor_path.is_file():
        print(f"[release-floor] FAIL: {floor_path} does not exist — run with --write", file=sys.stderr)
        return 1

    fence_results = measure_fences(repo_root, args.python)
    for fr in fence_results:
        print(f"[release-floor] fence {fr.name}: {'PASS' if fr.ok else 'FAIL'} (exit {fr.returncode})")
        if not fr.ok:
            print(f"    {fr.stderr_tail}", file=sys.stderr)

    if not census_path.is_file():
        print(f"[release-floor] FAIL: {census_path} not found", file=sys.stderr)
        return 1
    census = json.loads(census_path.read_text(encoding="utf-8"))

    try:
        if args.unit_junit:
            # CI path: the `unit` job of this same run already measured the suite; read its JUnit.
            unit_passed, unit_violations, unit_raw = measure_unit_tests_from_junit(
                repo_root, args.unit_junit, evidence_dir=args.unit_evidence_dir
            )
            print(f"[release-floor] unit tests (JUnit reports of this run):\n{unit_raw}")
        else:
            # Local path: no shard artifacts around, so measure the suite here as before.
            if args.unit_evidence_dir is None:
                unit_counts, unit_rc, unit_raw = measure_unit_tests(repo_root, args.python)
            else:
                unit_counts, unit_rc, unit_raw = measure_unit_tests(
                    repo_root, args.python, evidence_dir=args.unit_evidence_dir
                )
            print(f"[release-floor] unit tests: {unit_raw!r} (exit {unit_rc})")
            unit_passed, unit_violations = evaluate_unit_tests(unit_counts, unit_rc, unit_raw)
    except UnitEvidenceError:
        print("[release-floor] FAIL — requested unit diagnostics could not be retained", file=sys.stderr)
        return 1
    if unit_violations:
        print("[release-floor] FAIL — unit-test measurement is not trustworthy:", file=sys.stderr)
        for v in unit_violations:
            print(f"  - {v.render()}", file=sys.stderr)
        return 1

    # `unit_passed` is None only together with a non-empty `unit_violations`, which the guard
    # above already returned on — so it is provably an int here. The assert makes that invariant
    # explicit for a reader (and for mypy, should `scripts/` ever enter the type-checked scope),
    # on the fail-closed path of a shipped gate. (GK-1 review note, Train D release-floor.)
    assert unit_passed is not None
    candidate = capability_vector_from_measurements(
        census, [(fr.name, fr.ok) for fr in fence_results], unit_passed
    )

    if args.write:
        failing = [fr for fr in fence_results if not fr.ok]
        if failing:
            print(
                "[release-floor] FAIL: refusing to --write a baseline while a fence is failing:",
                file=sys.stderr,
            )
            for fr in failing:
                print(f"  - {fr.name} exit={fr.returncode}\n    {fr.stderr_tail}", file=sys.stderr)
            return 1
        doc = build_floor_document(candidate)
        floor_path.parent.mkdir(parents=True, exist_ok=True)
        floor_path.write_text(render_floor_json(doc), encoding="utf-8")
        print(f"[release-floor] WRITE: {candidate.to_json()} -> {floor_path}")
        return 0

    # Default (and --check): verify only, never mutate.
    if not floor_path.is_file():
        print(f"[release-floor] FAIL: {floor_path} does not exist — run with --write", file=sys.stderr)
        return 1
    baseline_doc = json.loads(floor_path.read_text(encoding="utf-8"))
    baseline = CapabilityVector.from_json(baseline_doc["capability_vector"])

    reg_violations = compare_vectors(candidate, baseline)
    if reg_violations:
        print(
            "[release-floor] FAIL — candidate is below the committed release-capability floor:",
            file=sys.stderr,
        )
        for v in reg_violations:
            print(f"  - {v.render()}", file=sys.stderr)
        print(f"  baseline:  {baseline.to_json()}", file=sys.stderr)
        print(f"  candidate: {candidate.to_json()}", file=sys.stderr)
        return 1

    print(
        f"[release-floor] PASS: candidate {candidate.to_json()} meets or exceeds floor {baseline.to_json()}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
