"""Derive browser shape facts from the existing Q1 registry; no authority grant."""

import hashlib
import json
import sys
from pathlib import Path

source = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(source))
from maezo.portal.contracts import models  # noqa: E402

model_path = source / "maezo/portal/contracts/models.py"
rows = [
    {"process": process, "task": task, "form": form, "source": status}
    for (process, task), (form, status) in sorted(models._BINDINGS.items())
]
inputs = {form: list(fields) for form, fields in sorted(models._INPUTS_BY_FORM.items())}
text = (
    "// Generated by scripts/generate-read-bindings.py from Q1 models.py.\n"
    f"// Source SHA-256: {hashlib.sha256(model_path.read_bytes()).hexdigest()}\n"
    "// Fixed DTO shapes only; this is not publisher, session, or decision authority.\n"
    "export const taskReadBindings = " + json.dumps(rows, ensure_ascii=False, indent=2) + " as const;\n\n"
    "export const taskReadInputs = " + json.dumps(inputs, ensure_ascii=False, indent=2) + " as const;\n"
)
target = Path(__file__).resolve().parents[1] / "src/taskReadBindings.ts"
if sys.argv[1:] == ["--check"]:
    if target.read_text() != text:
        raise SystemExit("Q1 browser binding artifact differs from the approved registry")
elif not sys.argv[1:]:
    target.write_text(text)
else:
    raise SystemExit("usage: generate-read-bindings.py [--check]")
