// Generated by scripts/generate-read-bindings.py from Q1 models.py.
// Source SHA-256: 6f6a9eff4c0fa668261f28def186d8c88ceaa44d5e184911b7f3c3497c083bf7
// Fixed DTO shapes only; this is not publisher, session, or decision authority.
export const taskReadBindings = [
  {
    "process": "SP-OP-AUTH-001",
    "task": "UT_AnaliseMedicoAuditor",
    "form": "auth_decisao",
    "source": "BPMN_FORMDATA"
  },
  {
    "process": "SP-OP-AUTH-001",
    "task": "UT_CoordenacaoAssume",
    "form": "auth_decisao",
    "source": "BPMN_FORMDATA"
  },
  {
    "process": "SP-OP-AUTH-001",
    "task": "UT_RegistrarParecerJunta",
    "form": "auth_junta",
    "source": "BPMN_FORMDATA"
  },
  {
    "process": "SP-OP-CANCEL-001",
    "task": "UT_AnaliseRescisao",
    "form": "cancel_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-CANCEL-001",
    "task": "UT_CoordenacaoCancelamento",
    "form": "cancel_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-CONTAS-001",
    "task": "UT_AnalistaContas",
    "form": "contas_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-CONTAS-001",
    "task": "UT_CoordenacaoContasAssume",
    "form": "contas_coordenacao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-ESCALATION-001",
    "task": "UT_SupervisorAssume",
    "form": "escalation",
    "source": "BPMN_FORMDATA"
  },
  {
    "process": "SP-OP-ESCALATION-001",
    "task": "UT_TratarEscalonamento",
    "form": "escalation",
    "source": "BPMN_FORMDATA"
  },
  {
    "process": "SP-OP-INADIMPLENCIA-001",
    "task": "UT_AnaliseInadimplencia",
    "form": "inad_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-INADIMPLENCIA-001",
    "task": "UT_CoordenacaoCobranca",
    "form": "inad_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-PAGTO-001",
    "task": "UT_AnaliseAdmissibilidade",
    "form": "pagto_admissibilidade",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-PROGRAMA-001",
    "task": "UT_CoordenacaoDecisao",
    "form": "programa_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-PROGRAMA-001",
    "task": "UT_DecisaoClinica",
    "form": "programa_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-RECURSO-001",
    "task": "UT_AnaliseRecursoAnalista",
    "form": "recurso_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-RECURSO-001",
    "task": "UT_CoordenacaoRecursoAssume",
    "form": "recurso_coordenacao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-RECURSO-001",
    "task": "UT_EscalonamentoPrazo",
    "form": "recurso_coordenacao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-RECURSO-001",
    "task": "UT_RevisaoAuditorMedico",
    "form": "recurso_auditor",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-REEMBOLSO-001",
    "task": "UT_AnaliseReembolso",
    "form": "reembolso_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-REEMBOLSO-001",
    "task": "UT_CoordenacaoReembolso",
    "form": "reembolso_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-REEMBOLSO-001",
    "task": "UT_DecidirPendenciaExpirada",
    "form": "reembolso_pendencia",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-REEMBOLSO-001",
    "task": "UT_RevisaoAuditorMedico",
    "form": "reembolso_auditor",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  }
] as const;

export const taskReadInputs = {
  "auth_decisao": [
    "decisao_auditor",
    "justificativa_clinica",
    "cid10_referencia",
    "fundamentacao_dut"
  ],
  "auth_junta": [
    "decisao_auditor",
    "justificativa_clinica",
    "cid10_referencia",
    "fundamentacao_dut"
  ],
  "cancel_decisao": [
    "decisao_cancelamento",
    "fundamentacao_contratual",
    "referencia_regulatoria",
    "comprovacao_notificacao_previa"
  ],
  "contas_coordenacao": [
    "decisao_contas",
    "justificativa_glosa",
    "codigo_glosa_tiss",
    "valor_glosado_centavos",
    "valor_liberado_centavos",
    "justificativa_devolucao",
    "decisao_coordenacao"
  ],
  "contas_decisao": [
    "decisao_contas",
    "justificativa_glosa",
    "codigo_glosa_tiss",
    "valor_glosado_centavos",
    "valor_liberado_centavos",
    "justificativa_devolucao"
  ],
  "escalation": [
    "resultado",
    "notas_resolucao"
  ],
  "inad_decisao": [
    "decisao_inadimplencia",
    "fundamentacao_contratual",
    "referencia_regulatoria",
    "comprovacao_notificacao_previa",
    "comprovacao_periodo_minimo",
    "data_efeito_iso"
  ],
  "pagto_admissibilidade": [
    "decisao_admissibilidade",
    "justificativa_recusa"
  ],
  "programa_decisao": [
    "decisao_programa",
    "motivo_desligamento_clinico",
    "referencia_clinica"
  ],
  "recurso_auditor": [
    "decisao_auditor_recurso",
    "parecer_auditor",
    "fundamentacao_indeferimento",
    "valor_glosa_mantido_centavos",
    "valor_deferido_centavos",
    "referencia_contratual"
  ],
  "recurso_coordenacao": [
    "decisao_recurso",
    "fundamentacao_indeferimento",
    "valor_glosa_mantido_centavos",
    "valor_deferido_centavos",
    "referencia_contratual",
    "desfecho_humano"
  ],
  "recurso_decisao": [
    "decisao_recurso",
    "fundamentacao_indeferimento",
    "valor_glosa_mantido_centavos",
    "valor_deferido_centavos",
    "referencia_contratual"
  ],
  "reembolso_auditor": [
    "decisao_reembolso",
    "valor_reembolso_aprovado_cents",
    "justificativa",
    "fundamentacao_contratual",
    "cid10_referencia",
    "parecer_auditor"
  ],
  "reembolso_decisao": [
    "decisao_reembolso",
    "valor_reembolso_aprovado_cents",
    "justificativa",
    "fundamentacao_contratual"
  ],
  "reembolso_pendencia": [
    "decisao_pendencia"
  ]
} as const;
