// Generated by scripts/generate-read-bindings.py from Q1 models.py.
// Source SHA-256: 58419e973db61224b03ad7d730b23d7ba231cd4030f9b23087f497d472095fe4
// Fixed DTO shapes only; this is not publisher, session, or decision authority.
export const taskReadBindings = [
  {
    "process": "SP-OP-ADEQUACAO-001",
    "task": "UT_CoordenacaoRede",
    "form": "adequacao_coordenacao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-ADEQUACAO-001",
    "task": "UT_DecisaoFallback",
    "form": "adequacao_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-ANS-SUBMIT-001",
    "task": "UT_CoordenacaoEnvioAssume",
    "form": "ans_coordenacao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-ANS-SUBMIT-001",
    "task": "UT_CorrigirPendenciaEnvio",
    "form": "ans_pendencia",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-ANS-SUBMIT-001",
    "task": "UT_RevisarEnvio",
    "form": "ans_revisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-ANS-SUBMIT-001",
    "task": "UT_RevisarEnvioJuridico",
    "form": "ans_revisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-ANS-SUBMIT-001",
    "task": "UT_TratarNack",
    "form": "ans_nack",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-AUTH-001",
    "task": "UT_AnaliseMedicoAuditor",
    "form": "auth_decisao",
    "source": "BPMN_FORMDATA"
  },
  {
    "process": "SP-OP-AUTH-001",
    "task": "UT_CoordenacaoAssume",
    "form": "auth_decisao",
    "source": "BPMN_FORMDATA"
  },
  {
    "process": "SP-OP-AUTH-001",
    "task": "UT_DecidirPendenciaExpirada",
    "form": "auth_pendencia",
    "source": "BPMN_FORMDATA"
  },
  {
    "process": "SP-OP-AUTH-001",
    "task": "UT_RegistrarParecerJunta",
    "form": "auth_junta",
    "source": "BPMN_FORMDATA"
  },
  {
    "process": "SP-OP-CANCEL-001",
    "task": "UT_AnaliseRescisao",
    "form": "cancel_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-CANCEL-001",
    "task": "UT_CoordenacaoCancelamento",
    "form": "cancel_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-CONTAS-001",
    "task": "UT_AnalistaContas",
    "form": "contas_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-CONTAS-001",
    "task": "UT_CoordenacaoContasAssume",
    "form": "contas_coordenacao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-CRED-001",
    "task": "UT_AnaliseCredenciamento",
    "form": "cred_cred",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-CRED-001",
    "task": "UT_AnaliseDescredenciamento",
    "form": "cred_descred",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-CRED-001",
    "task": "UT_CoordenacaoRedeCred",
    "form": "cred_cred",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-CRED-001",
    "task": "UT_CoordenacaoRedeDescred",
    "form": "cred_descred",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-ESCALATION-001",
    "task": "UT_SupervisorAssume",
    "form": "escalation",
    "source": "BPMN_FORMDATA"
  },
  {
    "process": "SP-OP-ESCALATION-001",
    "task": "UT_TratarEscalonamento",
    "form": "escalation",
    "source": "BPMN_FORMDATA"
  },
  {
    "process": "SP-OP-FRAUDE-001",
    "task": "UT_CoordenacaoInvestigacao",
    "form": "fraude_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-FRAUDE-001",
    "task": "UT_DecisaoInvestigador",
    "form": "fraude_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-FRAUDE-001",
    "task": "UT_RevisaoReferral",
    "form": "fraude_referral",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-INADIMPLENCIA-001",
    "task": "UT_AnaliseInadimplencia",
    "form": "inad_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-INADIMPLENCIA-001",
    "task": "UT_CoordenacaoCobranca",
    "form": "inad_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-LGPD-DSR-001",
    "task": "UT_RevisaoDpo",
    "form": "lgpd_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-NIP-001",
    "task": "UT_CoordenacaoNip",
    "form": "nip_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-NIP-001",
    "task": "UT_ElaborarRespostaNip",
    "form": "nip_minuta",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-NIP-001",
    "task": "UT_RevisaoJuridicaNip",
    "form": "nip_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-PAGTO-001",
    "task": "UT_AnaliseAdmissibilidade",
    "form": "pagto_admissibilidade",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-PAGTO-001",
    "task": "UT_AprovacaoAlcada",
    "form": "pagto_aprovacao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-PAGTO-001",
    "task": "UT_CoordenacaoAlcada",
    "form": "pagto_coordenacao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-PROGRAMA-001",
    "task": "UT_CoordenacaoDecisao",
    "form": "programa_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-PROGRAMA-001",
    "task": "UT_DecisaoClinica",
    "form": "programa_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-RECURSO-001",
    "task": "UT_AnaliseRecursoAnalista",
    "form": "recurso_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-RECURSO-001",
    "task": "UT_CoordenacaoRecursoAssume",
    "form": "recurso_coordenacao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-RECURSO-001",
    "task": "UT_EscalonamentoPrazo",
    "form": "recurso_coordenacao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-RECURSO-001",
    "task": "UT_RevisaoAuditorMedico",
    "form": "recurso_auditor",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-REEMBOLSO-001",
    "task": "UT_AnaliseReembolso",
    "form": "reembolso_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-REEMBOLSO-001",
    "task": "UT_CoordenacaoReembolso",
    "form": "reembolso_decisao",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-REEMBOLSO-001",
    "task": "UT_DecidirPendenciaExpirada",
    "form": "reembolso_pendencia",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  },
  {
    "process": "SP-OP-REEMBOLSO-001",
    "task": "UT_RevisaoAuditorMedico",
    "form": "reembolso_auditor",
    "source": "BPMN_TASK_DOCUMENTATION_DRAFT_VERIFY"
  }
] as const;

export const taskReadInputs = {
  "adequacao_coordenacao": [
    "decisao_coordenacao",
    "decisao_remediacao",
    "tipo_fallback",
    "justificativa_fallback",
    "referencia_regulatoria",
    "estimativa_custo_cents"
  ],
  "adequacao_decisao": [
    "decisao_remediacao",
    "tipo_fallback",
    "justificativa_fallback",
    "referencia_regulatoria",
    "estimativa_custo_cents"
  ],
  "ans_coordenacao": [
    "decisao_envio",
    "justificativa_adiamento"
  ],
  "ans_nack": [
    "decisao_nack"
  ],
  "ans_pendencia": [
    "dataset_complete",
    "schema_valid",
    "lgpd_anonimizado"
  ],
  "ans_revisao": [
    "decisao_envio",
    "justificativa_adiamento"
  ],
  "auth_decisao": [
    "decisao_auditor",
    "justificativa_clinica",
    "cid10_referencia",
    "fundamentacao_dut"
  ],
  "auth_junta": [
    "decisao_auditor",
    "justificativa_clinica",
    "cid10_referencia",
    "fundamentacao_dut"
  ],
  "auth_pendencia": [
    "decisao_pendencia"
  ],
  "cancel_decisao": [
    "decisao_cancelamento",
    "fundamentacao_contratual",
    "referencia_regulatoria",
    "comprovacao_notificacao_previa"
  ],
  "contas_coordenacao": [
    "decisao_contas",
    "justificativa_glosa",
    "codigo_glosa_tiss",
    "valor_glosado_centavos",
    "valor_liberado_centavos",
    "justificativa_devolucao",
    "decisao_coordenacao"
  ],
  "contas_decisao": [
    "decisao_contas",
    "justificativa_glosa",
    "codigo_glosa_tiss",
    "valor_glosado_centavos",
    "valor_liberado_centavos",
    "justificativa_devolucao"
  ],
  "cred_cred": [
    "decisao_cred",
    "fundamentacao",
    "referencia_regulatoria",
    "data_efeito_iso"
  ],
  "cred_descred": [
    "decisao_cred",
    "fundamentacao",
    "referencia_regulatoria",
    "comprovacao_notificacao_previa",
    "plano_substituicao",
    "data_efeito_iso"
  ],
  "escalation": [
    "resultado",
    "notas_resolucao"
  ],
  "fraude_decisao": [
    "decisao_fraude",
    "fundamentacao_investigacao",
    "indicadores_fundamentantes",
    "referencia_normativa",
    "destino_referral"
  ],
  "fraude_referral": [
    "destino_referral"
  ],
  "inad_decisao": [
    "decisao_inadimplencia",
    "fundamentacao_contratual",
    "referencia_regulatoria",
    "comprovacao_notificacao_previa",
    "comprovacao_periodo_minimo",
    "data_efeito_iso"
  ],
  "lgpd_decisao": [
    "decisao_dsr",
    "fundamentacao_legal"
  ],
  "nip_decisao": [
    "decisao_nip",
    "fundamentacao_regulatoria",
    "referencia_negativa_original",
    "texto_resposta_nip"
  ],
  "nip_minuta": [
    "texto_resposta_nip"
  ],
  "pagto_admissibilidade": [
    "decisao_admissibilidade",
    "justificativa_recusa"
  ],
  "pagto_aprovacao": [
    "decisao_pagamento",
    "valor_aprovado_cents",
    "justificativa_aprovacao",
    "justificativa_recusa"
  ],
  "pagto_coordenacao": [
    "decisao_coordenacao",
    "decisao_pagamento",
    "valor_aprovado_cents",
    "justificativa_aprovacao",
    "justificativa_recusa"
  ],
  "programa_decisao": [
    "decisao_programa",
    "motivo_desligamento_clinico",
    "referencia_clinica"
  ],
  "recurso_auditor": [
    "decisao_auditor_recurso",
    "parecer_auditor",
    "fundamentacao_indeferimento",
    "valor_glosa_mantido_centavos",
    "valor_deferido_centavos",
    "referencia_contratual"
  ],
  "recurso_coordenacao": [
    "decisao_recurso",
    "fundamentacao_indeferimento",
    "valor_glosa_mantido_centavos",
    "valor_deferido_centavos",
    "referencia_contratual",
    "desfecho_humano"
  ],
  "recurso_decisao": [
    "decisao_recurso",
    "fundamentacao_indeferimento",
    "valor_glosa_mantido_centavos",
    "valor_deferido_centavos",
    "referencia_contratual"
  ],
  "reembolso_auditor": [
    "decisao_reembolso",
    "valor_reembolso_aprovado_cents",
    "justificativa",
    "fundamentacao_contratual",
    "cid10_referencia",
    "parecer_auditor"
  ],
  "reembolso_decisao": [
    "decisao_reembolso",
    "valor_reembolso_aprovado_cents",
    "justificativa",
    "fundamentacao_contratual"
  ],
  "reembolso_pendencia": [
    "decisao_pendencia"
  ]
} as const;
