package br.com.maezo.workload;

import static org.junit.jupiter.api.Assertions.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

/** Finite protocol controls. No engine, database authority or task lifetime is simulated. */
class NativeV2ProfileTest {
  static final String REF="A".repeat(43),DIGEST="a".repeat(64);
  static Map<String,Object> identity(){return Map.of("tenant","tenant-test","environment","test","workload","fixture-worker","workload_version","1","issuer","fixture-issuer","subject","fixture-subject","origin","verified_mtls");}
  static Map<String,Object> command(String op){return Map.of("engine","default","database_incarnation","00000000-0000-0000-0000-000000000001","identity",identity(),"native_user","fixture-worker","operation",op,"capability_digest",DIGEST,"command_id",REF,"request_digest",DIGEST,"activation_ref","fixture-activation");}
  static Map<String,Object> reference(long revision){return Map.of("acquisition_ref",REF,"lease_revision",revision);}
  static Map<String,Object> snapshot(String role,long revision,String state){return Map.of("role",role,"task_ref","fixture-task","acquisition_ref",REF,"lease_revision",revision,"lock_expires_at",1000L,"state",state);}
  static Map<String,Object> receipt(String op){var r=new HashMap<String,Object>();r.put("receipt_ref",REF);r.put("state","committed");r.put("command",command(op));r.put("resource_ref_digest",NativeOutcomeV2.pointerDigest("fixture-task"));r.put("source_ref_digest",NativeOutcomeV2.pointerDigest(""));r.put("resource_acquisition",null);r.put("source_acquisition",null);r.put("acquisitions",List.of());return r;}
  @Test void generatedReferencesHaveCanonicalEntropyWidth(){var refs=new HashSet<String>();for(int i=0;i<128;i++){String v=NativeOutcomeV2.newRef();assertEquals(v,NativeOutcomeV2.ref(Map.of("r",v),"r"));assertTrue(refs.add(v));}}
  @ParameterizedTest @ValueSource(strings={"","abc","AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB","+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"})
  void malformedReferencesRefuse(String value){assertThrows(Refused.class,()->NativeOutcomeV2.ref(Map.of("r",value),"r"));}
  @Test void referenceRejectsMissingUnknownAndNonIntegralRevision(){for(Object v:List.of(0L,-1L,1.0,true,"1"))assertThrows(Refused.class,()->NativeOutcomeV2.reference(Map.of("acquisition_ref",REF,"lease_revision",v)));assertThrows(Refused.class,()->NativeOutcomeV2.reference(Map.of("acquisition_ref",REF)));assertThrows(Refused.class,()->NativeOutcomeV2.reference(Map.of("acquisition_ref",REF,"lease_revision",1L,"extra",true)));assertEquals(Long.MAX_VALUE,NativeOutcomeV2.reference(reference(Long.MAX_VALUE)).get("lease_revision"));}
  @Test void rawRequestDigestDoesNotNormalizeTransport(){assertNotEquals(NativeOutcomeV2.bodyDigest("{\"a\":1}".getBytes(StandardCharsets.UTF_8)),NativeOutcomeV2.bodyDigest("{ \"a\":1}".getBytes(StandardCharsets.UTF_8)));}
  @Test void duplicateHasHistoricalReceiptAndNoProjection(){var c=command("read_active");var r=receipt("read_active");var body=Json.parse(NativeOutcomeV2.operation(c,"duplicate",r,Map.of("secret","never"),List.of()).bytes());assertNull(body.get("result"));assertEquals(r,body.get("receipt"));assertEquals(Set.of("protocol","command","status","receipt","result"),body.keySet());}
  @Test void outcomeHasOnlyExactHistoryUnion(){var q=Map.<String,Object>of("recovery_capability_digest",DIGEST,"reader_activation_ref","current-reader","command",command("read_active"));var body=Json.parse(NativeOutcomeV2.outcome(q,DIGEST,"committed",receipt("read_active")).bytes());assertEquals(Set.of("protocol","recovery_capability_digest","reader_activation_ref","query_digest","command","status","receipt"),body.keySet());assertFalse(body.containsKey("result"));}
  @ParameterizedTest @ValueSource(strings={"conflict","unavailable"})
  void nonsuccessCannotContainReceipt(String state){assertThrows(Refused.class,()->NativeOutcomeV2.operation(command("read_active"),state,receipt("read_active"),null,List.of()));assertNull(Json.parse(NativeOutcomeV2.operation(command("read_active"),state,null,null,List.of()).bytes()).get("receipt"));}
  @Test void mismatchedCommandReceiptRefuses(){var r=receipt("read_active");assertThrows(Refused.class,()->NativeOutcomeV2.receipt(r,command("start")));}
  @Test void missingPublicationNeverClaimsRollback(){var p=new NativeOutcomeV2.Publication();assertThrows(Refused.class,p::committed);assertDoesNotThrow(p::publish);assertThrows(Refused.class,p::committed);}
  @Test void publicationIsPreparedOnceAndDoesNotSerializeAfterCommit(){var p=new NativeOutcomeV2.Publication();byte[] b={1,2};var e=new NativeOutcomeV2.Encoded(200,b);p.prepare(e);b[0]=9;assertThrows(Refused.class,()->p.prepare(e));assertDoesNotThrow(p::publish);assertArrayEquals(new byte[]{1,2},p.committed().bytes());byte[] out=p.committed().bytes();out[0]=8;assertArrayEquals(new byte[]{1,2},p.committed().bytes());}
  @Test void renewalReceiptCarriesAdvancedRevisionAndMayShortenExpiry(){var r=receipt("external_extend_lock");r.put("resource_acquisition",reference(3));r.put("acquisitions",List.of(snapshot("resource",4,"live")));assertEquals(r,NativeOutcomeV2.receipt(r,command("external_extend_lock")));r.put("acquisitions",List.of(snapshot("resource",3,"live")));assertThrows(Refused.class,()->NativeOutcomeV2.receipt(r,command("external_extend_lock")));}
  @ParameterizedTest @ValueSource(strings={"external_complete","external_failure","external_bpmn_error","external_unlock"})
  void terminalReceiptsCloseTheConsumedGeneration(String op){var r=receipt(op);r.put("resource_acquisition",reference(3));r.put("acquisitions",List.of(snapshot("resource",3,"closed")));assertEquals(r,NativeOutcomeV2.receipt(r,command(op)));r.put("acquisitions",List.of(snapshot("resource",3,"live")));assertThrows(Refused.class,()->NativeOutcomeV2.receipt(r,command(op)));}
  @Test void sameRowSourceAndResourceMustAgreeAfterRenewal(){var r=receipt("external_extend_lock");r.put("resource_acquisition",reference(3));r.put("source_acquisition",reference(3));r.put("source_ref_digest",NativeOutcomeV2.pointerDigest("fixture-task"));r.put("acquisitions",List.of(snapshot("resource",4,"live"),snapshot("source",4,"live")));NativeOutcomeV2.receipt(r,command("external_extend_lock"));r.put("acquisitions",List.of(snapshot("resource",4,"live"),snapshot("source",3,"live")));assertThrows(Refused.class,()->NativeOutcomeV2.receipt(r,command("external_extend_lock")));}
  @Test void duplicateSnapshotAndForeignPointerRefuse(){var r=receipt("fetch_lock");r.put("acquisitions",List.of(snapshot("resource",1,"live"),snapshot("resource",1,"live")));var fetchReceipt=r;assertThrows(Refused.class,()->NativeOutcomeV2.receipt(fetchReceipt,command("fetch_lock")));r=receipt("external_unlock");r.put("resource_acquisition",reference(1));r.put("resource_ref_digest",DIGEST);r.put("acquisitions",List.of(snapshot("resource",1,"closed")));var bad=r;assertThrows(Refused.class,()->NativeOutcomeV2.receipt(bad,command("external_unlock")));}
  @Test void executedMembershipMustMatchReceiptExactly(){var r=receipt("fetch_lock");r.put("acquisitions",List.of(snapshot("resource",1,"live")));assertThrows(Refused.class,()->NativeOutcomeV2.operation(command("fetch_lock"),"executed",r,List.of(),List.of()));}
  @Test void closedWireRejectsUnknownReceiptKeys(){var r=receipt("read_active");r.put("current_state","live");assertThrows(Refused.class,()->NativeOutcomeV2.receipt(r,command("read_active")));}
  static jakarta.servlet.http.HttpServletRequest route(String uri,String method,String type,String query,jakarta.servlet.DispatcherType dispatch){
    return (jakarta.servlet.http.HttpServletRequest)java.lang.reflect.Proxy.newProxyInstance(NativeV2ProfileTest.class.getClassLoader(),new Class<?>[]{jakarta.servlet.http.HttpServletRequest.class},(proxy,m,args)->switch(m.getName()){
      case "getRequestURI"->uri;case "getContextPath"->"/maezo-workload";case "getServletPath"->"/v2";case "getPathInfo"->uri.substring("/maezo-workload/v2".length());case "getMethod"->method;case "getContentType"->type;case "getQueryString"->query;case "getDispatcherType"->dispatch;case "isAsyncStarted"->false;case "getContentLengthLong"->0L;default->null;});
  }
  @ParameterizedTest @ValueSource(strings={"/operations","/outcomes"})
  void exactV2PostRoutesAcceptOnlyTheProfile(String path){assertTrue(BoundaryPolicyV2.route(route("/maezo-workload/v2"+path,"POST","application/json",null,jakarta.servlet.DispatcherType.REQUEST)));}
  @ParameterizedTest @ValueSource(strings={"/operations/","/operations;x=1","/Operations","/operations%2f","/unknown"})
  void aliasesDoNotNegotiateOrNormalize(String path){assertThrows(Refused.class,()->BoundaryPolicyV2.route(route("/maezo-workload/v2"+path,"POST","application/json",null,jakarta.servlet.DispatcherType.REQUEST)));}
  @Test void forwardedQueryAndWrongContentTypeRefuse(){assertThrows(Refused.class,()->BoundaryPolicyV2.route(route("/maezo-workload/v2/operations","POST","application/json","x=1",jakarta.servlet.DispatcherType.REQUEST)));assertThrows(Refused.class,()->BoundaryPolicyV2.route(route("/maezo-workload/v2/operations","POST","application/json",null,jakarta.servlet.DispatcherType.FORWARD)));assertThrows(Refused.class,()->BoundaryPolicyV2.route(route("/maezo-workload/v2/operations","POST","text/plain",null,jakarta.servlet.DispatcherType.REQUEST)));}
  @Test void readinessIsGetOnly(){assertTrue(BoundaryPolicyV2.route(route("/maezo-workload/v2/readiness","GET",null,null,jakarta.servlet.DispatcherType.REQUEST)));assertThrows(Refused.class,()->BoundaryPolicyV2.route(route("/maezo-workload/v2/readiness","POST","application/json",null,jakarta.servlet.DispatcherType.REQUEST)));}
}
