"""Owned E03 runtime lifecycle: real native query, PostgreSQL admission and relay.

The caller supplies already provisioned, purpose-separated infrastructure. Startup
checks the persistent source's acknowledged activation; each native request separately
checks its actual installation and current authority. No credentials or owner grants
are generated by composition, and no global services start on module import.
"""

from __future__ import annotations

import asyncio

from maezo.portal.api.session import HumanSessionResolver

from .assignment_receipt import NativeAssignmentReceiptAuthority
from .assignment_transport import NativeAssignmentClient
from .credentials import HumanCommandCredentialPartition
from .decision import BoundDecisionPorts
from .gateway import HumanGateway
from .models import Scope
from .outbox import PostgresGovernedAssignmentAdmission, PostgresHumanOutbox
from .ports import BoundGovernedAssignmentPorts, BoundHumanPorts
from .receipt import BoundReceiptPorts
from .relay import HumanCommandRelay, RelaySettings
from .transport import MTLSHumanEngineTransport


class AssignmentRuntime:
    def __init__(
        self,
        *,
        scope: Scope,
        client: NativeAssignmentClient,
        outbox: PostgresHumanOutbox,
        transport: MTLSHumanEngineTransport,
        credentials: HumanCommandCredentialPartition,
        receipt_authority: NativeAssignmentReceiptAuthority,
        relay_settings: RelaySettings,
        legacy_ports: BoundHumanPorts | None = None,
        decision_ports: BoundDecisionPorts | None = None,
    ) -> None:
        from .errors import GatewayRefusalError

        if not isinstance(receipt_authority, NativeAssignmentReceiptAuthority):
            raise GatewayRefusalError("production_capabilities_unavailable")
        if any(value.scope != scope for value in (client, outbox, transport, receipt_authority)):
            raise GatewayRefusalError("credential_scope_mismatch")
        credentials.for_workload(scope)
        self.scope, self._client, self._outbox = Scope.model_validate(scope), client, outbox
        self._credentials, self._receipt_authority = credentials, receipt_authority
        self._legacy_ports, self._decision_ports = legacy_ports, decision_ports
        self._relay = HumanCommandRelay(outbox=outbox, transport=transport, settings=relay_settings)
        self._stop = asyncio.Event()
        self._runner: asyncio.Task[None] | None = None
        self._closed = False

    @property
    def decision_ports(self) -> BoundDecisionPorts | None:
        """The bound decision composition, or `None` while decisions stay refused.

        Exposed for evidence: whether `submit_decision` can run at all is a deployment
        fact a test must be able to assert without reaching into private state.
        """
        return self._decision_ports

    async def start(self) -> None:
        from .errors import GatewayRefusalError

        if self._closed or self._runner is not None:
            raise GatewayRefusalError("production_capabilities_unavailable")
        await self._client._active()
        self._client._transport._signing.guard()
        self._runner = asyncio.create_task(self._relay.run(self._stop), name="human-assignment-relay")

    def build(self, resolver: HumanSessionResolver) -> HumanGateway:
        from .errors import GatewayRefusalError

        if self._closed or self._runner is None or self._runner.done():
            raise GatewayRefusalError("production_capabilities_unavailable")
        return HumanGateway(
            resolver=resolver,
            scope=self.scope,
            ports=self._legacy_ports,
            credentials=self._credentials,
            receipt_ports=BoundReceiptPorts(self._outbox, self._receipt_authority),
            decision_ports=self._decision_ports,
            governed_assignment_ports=BoundGovernedAssignmentPorts(
                self._client,
                self._client,
                self._client,
                PostgresGovernedAssignmentAdmission(self._outbox, self._client),
            ),
        )

    async def close(self) -> None:
        self._closed = True
        self._stop.set()
        try:
            if self._runner is not None:
                await self._runner  # owned in-flight delivery completes/reconciles before resources close
        finally:
            try:
                await self._client._transport.aclose()
            finally:
                if self._receipt_authority._transport is not self._client._transport:
                    await self._receipt_authority._transport.aclose()
        # DB pools and session/source engines remain owned by the deployment composition
        # that supplied them; this runtime never closes another package's pools.
